#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CAGLIANA")]
public partial class U_StoricoVenditeArticoloPerAgentePerCliente_LINQDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Definizioni metodo Extensibility
  partial void OnCreated();
  partial void InsertU_StoricoVenditeArticoloPerAgentePerCliente_VIew(U_StoricoVenditeArticoloPerAgentePerCliente_VIew instance);
  partial void UpdateU_StoricoVenditeArticoloPerAgentePerCliente_VIew(U_StoricoVenditeArticoloPerAgentePerCliente_VIew instance);
  partial void DeleteU_StoricoVenditeArticoloPerAgentePerCliente_VIew(U_StoricoVenditeArticoloPerAgentePerCliente_VIew instance);
  #endregion
	
	public U_StoricoVenditeArticoloPerAgentePerCliente_LINQDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["GestionaleConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public U_StoricoVenditeArticoloPerAgentePerCliente_LINQDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public U_StoricoVenditeArticoloPerAgentePerCliente_LINQDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public U_StoricoVenditeArticoloPerAgentePerCliente_LINQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public U_StoricoVenditeArticoloPerAgentePerCliente_LINQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<U_StoricoVenditeArticoloPerAgentePerCliente_VIew> U_StoricoVenditeArticoloPerAgentePerCliente_VIew
	{
		get
		{
			return this.GetTable<U_StoricoVenditeArticoloPerAgentePerCliente_VIew>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.U_StoricoVenditeArticoloPerAgentePerCliente_VIew")]
public partial class U_StoricoVenditeArticoloPerAgentePerCliente_VIew : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Nullable<double> _Prezzo;
	
	private System.Nullable<float> _Sconto;
	
	private System.Nullable<float> _Sconto2;
	
	private System.Nullable<System.DateTime> _DataOrdCli;
	
	private System.Nullable<double> _QtaOrd;
	
	private string _CodArt;
	
	private string _Descrizione;
	
	private string _Agente;
	
	private string _CodCli;
	
	private System.Nullable<long> _IdRow;
	
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPrezzoChanging(System.Nullable<double> value);
    partial void OnPrezzoChanged();
    partial void OnScontoChanging(System.Nullable<float> value);
    partial void OnScontoChanged();
    partial void OnSconto2Changing(System.Nullable<float> value);
    partial void OnSconto2Changed();
    partial void OnDataOrdCliChanging(System.Nullable<System.DateTime> value);
    partial void OnDataOrdCliChanged();
    partial void OnQtaOrdChanging(System.Nullable<double> value);
    partial void OnQtaOrdChanged();
    partial void OnCodArtChanging(string value);
    partial void OnCodArtChanged();
    partial void OnDescrizioneChanging(string value);
    partial void OnDescrizioneChanged();
    partial void OnAgenteChanging(string value);
    partial void OnAgenteChanged();
    partial void OnCodCliChanging(string value);
    partial void OnCodCliChanged();
    partial void OnIdRowChanging(System.Nullable<long> value);
    partial void OnIdRowChanged();
    #endregion
	
	public U_StoricoVenditeArticoloPerAgentePerCliente_VIew()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prezzo", DbType="Float")]
	public System.Nullable<double> Prezzo
	{
		get
		{
			return this._Prezzo;
		}
		set
		{
			if ((this._Prezzo != value))
			{
				this.OnPrezzoChanging(value);
				this.SendPropertyChanging();
				this._Prezzo = value;
				this.SendPropertyChanged("Prezzo");
				this.OnPrezzoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sconto", DbType="Real")]
	public System.Nullable<float> Sconto
	{
		get
		{
			return this._Sconto;
		}
		set
		{
			if ((this._Sconto != value))
			{
				this.OnScontoChanging(value);
				this.SendPropertyChanging();
				this._Sconto = value;
				this.SendPropertyChanged("Sconto");
				this.OnScontoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sconto2", DbType="Real")]
	public System.Nullable<float> Sconto2
	{
		get
		{
			return this._Sconto2;
		}
		set
		{
			if ((this._Sconto2 != value))
			{
				this.OnSconto2Changing(value);
				this.SendPropertyChanging();
				this._Sconto2 = value;
				this.SendPropertyChanged("Sconto2");
				this.OnSconto2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataOrdCli", DbType="DateTime")]
	public System.Nullable<System.DateTime> DataOrdCli
	{
		get
		{
			return this._DataOrdCli;
		}
		set
		{
			if ((this._DataOrdCli != value))
			{
				this.OnDataOrdCliChanging(value);
				this.SendPropertyChanging();
				this._DataOrdCli = value;
				this.SendPropertyChanged("DataOrdCli");
				this.OnDataOrdCliChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QtaOrd", DbType="Float")]
	public System.Nullable<double> QtaOrd
	{
		get
		{
			return this._QtaOrd;
		}
		set
		{
			if ((this._QtaOrd != value))
			{
				this.OnQtaOrdChanging(value);
				this.SendPropertyChanging();
				this._QtaOrd = value;
				this.SendPropertyChanged("QtaOrd");
				this.OnQtaOrdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodArt", DbType="VarChar(20)")]
	public string CodArt
	{
		get
		{
			return this._CodArt;
		}
		set
		{
			if ((this._CodArt != value))
			{
				this.OnCodArtChanging(value);
				this.SendPropertyChanging();
				this._CodArt = value;
				this.SendPropertyChanged("CodArt");
				this.OnCodArtChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descrizione", DbType="VarChar(40)")]
	public string Descrizione
	{
		get
		{
			return this._Descrizione;
		}
		set
		{
			if ((this._Descrizione != value))
			{
				this.OnDescrizioneChanging(value);
				this.SendPropertyChanging();
				this._Descrizione = value;
				this.SendPropertyChanged("Descrizione");
				this.OnDescrizioneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Agente", DbType="VarChar(4)")]
	public string Agente
	{
		get
		{
			return this._Agente;
		}
		set
		{
			if ((this._Agente != value))
			{
				this.OnAgenteChanging(value);
				this.SendPropertyChanging();
				this._Agente = value;
				this.SendPropertyChanged("Agente");
				this.OnAgenteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodCli", DbType="VarChar(10)")]
	public string CodCli
	{
		get
		{
			return this._CodCli;
		}
		set
		{
			if ((this._CodCli != value))
			{
				this.OnCodCliChanging(value);
				this.SendPropertyChanging();
				this._CodCli = value;
				this.SendPropertyChanged("CodCli");
				this.OnCodCliChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRow", DbType="BigInt", IsPrimaryKey=true)]
	public System.Nullable<long> IdRow
	{
		get
		{
			return this._IdRow;
		}
		set
		{
			if ((this._IdRow != value))
			{
				this.OnIdRowChanging(value);
				this.SendPropertyChanging();
				this._IdRow = value;
				this.SendPropertyChanged("IdRow");
				this.OnIdRowChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
