#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTRA.Age_Ordini.AppCode
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CAGLIANA")]
	public partial class U_ViewBozzeOrdini_ViewDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definizioni metodo Extensibility
    partial void OnCreated();
    partial void InsertU_ViewBozzeOrdini_View(U_ViewBozzeOrdini_View instance);
    partial void UpdateU_ViewBozzeOrdini_View(U_ViewBozzeOrdini_View instance);
    partial void DeleteU_ViewBozzeOrdini_View(U_ViewBozzeOrdini_View instance);
    #endregion
		
		public U_ViewBozzeOrdini_ViewDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["GestionaleConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public U_ViewBozzeOrdini_ViewDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public U_ViewBozzeOrdini_ViewDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public U_ViewBozzeOrdini_ViewDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public U_ViewBozzeOrdini_ViewDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<U_ViewBozzeOrdini_View> U_ViewBozzeOrdini_View
		{
			get
			{
				return this.GetTable<U_ViewBozzeOrdini_View>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.U_ViewBozzeOrdini_View")]
	public partial class U_ViewBozzeOrdini_View : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Denom;
		
		private int _ID;
		
		private System.Nullable<System.DateTime> _OrdDat;
		
		private string _CodCli;
		
		private string _U_User_Web;
		
		private System.Nullable<short> _FlagEvaso;
		
		private string _Descrizione;
		
		private string _Url;
		
		private string _U_Portale;
		
		private string _DescrAgente;
		
		private bool _FlagStampa;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDenomChanging(string value);
    partial void OnDenomChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnOrdDatChanging(System.Nullable<System.DateTime> value);
    partial void OnOrdDatChanged();
    partial void OnCodCliChanging(string value);
    partial void OnCodCliChanged();
    partial void OnU_User_WebChanging(string value);
    partial void OnU_User_WebChanged();
    partial void OnFlagEvasoChanging(System.Nullable<short> value);
    partial void OnFlagEvasoChanged();
    partial void OnDescrizioneChanging(string value);
    partial void OnDescrizioneChanged();
    partial void OnUrlChanging(string value);
    partial void OnUrlChanged();
    partial void OnU_PortaleChanging(string value);
    partial void OnU_PortaleChanged();
    partial void OnDescrAgenteChanging(string value);
    partial void OnDescrAgenteChanged();
    partial void OnFlagStampaChanging(bool value);
    partial void OnFlagStampaChanged();
    #endregion
		
		public U_ViewBozzeOrdini_View()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Denom", DbType="VarChar(60)")]
		public string Denom
		{
			get
			{
				return this._Denom;
			}
			set
			{
				if ((this._Denom != value))
				{
					this.OnDenomChanging(value);
					this.SendPropertyChanging();
					this._Denom = value;
					this.SendPropertyChanged("Denom");
					this.OnDenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrdDat", DbType="DateTime")]
		public System.Nullable<System.DateTime> OrdDat
		{
			get
			{
				return this._OrdDat;
			}
			set
			{
				if ((this._OrdDat != value))
				{
					this.OnOrdDatChanging(value);
					this.SendPropertyChanging();
					this._OrdDat = value;
					this.SendPropertyChanged("OrdDat");
					this.OnOrdDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodCli", DbType="VarChar(10)")]
		public string CodCli
		{
			get
			{
				return this._CodCli;
			}
			set
			{
				if ((this._CodCli != value))
				{
					this.OnCodCliChanging(value);
					this.SendPropertyChanging();
					this._CodCli = value;
					this.SendPropertyChanged("CodCli");
					this.OnCodCliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_User_Web", DbType="VarChar(50)")]
		public string U_User_Web
		{
			get
			{
				return this._U_User_Web;
			}
			set
			{
				if ((this._U_User_Web != value))
				{
					this.OnU_User_WebChanging(value);
					this.SendPropertyChanging();
					this._U_User_Web = value;
					this.SendPropertyChanged("U_User_Web");
					this.OnU_User_WebChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlagEvaso", DbType="SmallInt")]
		public System.Nullable<short> FlagEvaso
		{
			get
			{
				return this._FlagEvaso;
			}
			set
			{
				if ((this._FlagEvaso != value))
				{
					this.OnFlagEvasoChanging(value);
					this.SendPropertyChanging();
					this._FlagEvaso = value;
					this.SendPropertyChanged("FlagEvaso");
					this.OnFlagEvasoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descrizione", DbType="NVarChar(50)")]
		public string Descrizione
		{
			get
			{
				return this._Descrizione;
			}
			set
			{
				if ((this._Descrizione != value))
				{
					this.OnDescrizioneChanging(value);
					this.SendPropertyChanging();
					this._Descrizione = value;
					this.SendPropertyChanged("Descrizione");
					this.OnDescrizioneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="NVarChar(MAX)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this.OnUrlChanging(value);
					this.SendPropertyChanging();
					this._Url = value;
					this.SendPropertyChanged("Url");
					this.OnUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_Portale", DbType="VarChar(1)")]
		public string U_Portale
		{
			get
			{
				return this._U_Portale;
			}
			set
			{
				if ((this._U_Portale != value))
				{
					this.OnU_PortaleChanging(value);
					this.SendPropertyChanging();
					this._U_Portale = value;
					this.SendPropertyChanged("U_Portale");
					this.OnU_PortaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescrAgente", DbType="VarChar(40)")]
		public string DescrAgente
		{
			get
			{
				return this._DescrAgente;
			}
			set
			{
				if ((this._DescrAgente != value))
				{
					this.OnDescrAgenteChanging(value);
					this.SendPropertyChanging();
					this._DescrAgente = value;
					this.SendPropertyChanged("DescrAgente");
					this.OnDescrAgenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlagStampa", DbType="Bit NOT NULL")]
		public bool FlagStampa
		{
			get
			{
				return this._FlagStampa;
			}
			set
			{
				if ((this._FlagStampa != value))
				{
					this.OnFlagStampaChanging(value);
					this.SendPropertyChanging();
					this._FlagStampa = value;
					this.SendPropertyChanged("FlagStampa");
					this.OnFlagStampaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
