//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTRA.Webservice_primo_online {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Webservice_primo_online.WebService_primoSoap")]
    public interface WebService_primoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/converttodaysweb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int converttodaysweb(int day, int month, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/converttodaysweb", ReplyAction="*")]
        System.Threading.Tasks.Task<int> converttodayswebAsync(int day, int month, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplication", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Multiplication(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplication", ReplyAction="*")]
        System.Threading.Tasks.Task<int> MultiplicationAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addTckCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int addTckCustomer(string CodCli, string OggettoTCK, string MotivoChiamata, int TCK_TipoRichiesta, int TCK_AreaCompetenza, int TCK_StatusChiamata, int TCK_PrioritaRichiesta, string NomePersonaRiferimento, string TelPersonaRiferimento, string MailPersonaRiferimento, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addTckCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<int> addTckCustomerAsync(string CodCli, string OggettoTCK, string MotivoChiamata, int TCK_TipoRichiesta, int TCK_AreaCompetenza, int TCK_StatusChiamata, int TCK_PrioritaRichiesta, string NomePersonaRiferimento, string TelPersonaRiferimento, string MailPersonaRiferimento, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addTckCustomerArray", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int addTckCustomerArray(INTRA.Webservice_primo_online.TCK_Ticket_WS TckPost, string SessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addTckCustomerArray", ReplyAction="*")]
        System.Threading.Tasks.Task<int> addTckCustomerArrayAsync(INTRA.Webservice_primo_online.TCK_Ticket_WS TckPost, string SessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMailAimXtype", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SendMailAimXtype(string from, string to, int CodRapportino, int TicketStatus_Template, string UserCrudTemplate, string MailTecnicoTemplate, string NomeTecnicoTemplate, int Attachments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMailAimXtype", ReplyAction="*")]
        System.Threading.Tasks.Task SendMailAimXtypeAsync(string from, string to, int CodRapportino, int TicketStatus_Template, string UserCrudTemplate, string MailTecnicoTemplate, string NomeTecnicoTemplate, int Attachments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendTicketMailAim", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SendTicketMailAim(int TicketId, int TicketStatus, string UserCrud, INTRA.Webservice_primo_online.TCK_Ticket_WS rapportini, string MailTecnico, string NomeTecnico, bool Responsabili, string TipoAllegato, string IdAllegato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendTicketMailAim", ReplyAction="*")]
        System.Threading.Tasks.Task SendTicketMailAimAsync(int TicketId, int TicketStatus, string UserCrud, INTRA.Webservice_primo_online.TCK_Ticket_WS rapportini, string MailTecnico, string NomeTecnico, bool Responsabili, string TipoAllegato, string IdAllegato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestSendEmai", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void TestSendEmai(string from, string to, string msg, string msgObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestSendEmai", ReplyAction="*")]
        System.Threading.Tasks.Task TestSendEmaiAsync(string from, string to, string msg, string msgObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckHostStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckHostStatus(string hostCodParam, string userNameCodParam, string passwordCodParam, string portCodParam, string SslModeCodParam, string EnableImplicitSslCodParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckHostStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CheckHostStatusAsync(string hostCodParam, string userNameCodParam, string passwordCodParam, string portCodParam, string SslModeCodParam, string EnableImplicitSslCodParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateNoteTecnico", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void UpdateNoteTecnico(int idTicket, string nota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateNoteTecnico", ReplyAction="*")]
        System.Threading.Tasks.Task UpdateNoteTecnicoAsync(int idTicket, string nota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStatusChiamata", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void UpdateStatusChiamata(int idTicket, int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStatusChiamata", ReplyAction="*")]
        System.Threading.Tasks.Task UpdateStatusChiamataAsync(int idTicket, int status);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TCK_Ticket_WS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codRapportinoField;
        
        private string codClienteField;
        
        private string societàField;
        
        private string pIvaField;
        
        private string indirizzoField;
        
        private string capField;
        
        private string localitàField;
        
        private string provinciaField;
        
        private string telefonoField;
        
        private string faxField;
        
        private string emailField;
        
        private string matricolaField;
        
        private string scalaField;
        
        private int tipoImpiantoField;
        
        private string personaDaContattareField;
        
        private int tipoChiamataField;
        
        private int areaAssField;
        
        private string motivoChiamataField;
        
        private string noteField;
        
        private string guastoRilevatoField;
        
        private string lavoroEseguitoField;
        
        private bool interventoChiusoField;
        
        private string osservazioniField;
        
        private string dataInterventoField;
        
        private string dataInsField;
        
        private string editUserField;
        
        private string createdOnField;
        
        private string updatedOnField;
        
        private string userField;
        
        private string oreField;
        
        private int statusRptField;
        
        private int idField;
        
        private string incaricatoCliField;
        
        private string immagineTxtField;
        
        private string percorsoImmagineField;
        
        private int tCK_TipoRichiestaField;
        
        private int tCK_AreaCompetenzaField;
        
        private int tCK_TipoEsecuzionePresuntaField;
        
        private int tCK_TipoEsecuzioneField;
        
        private int tCK_StatusChiamataField;
        
        private int tCK_StatusChiamataChiusuraField;
        
        private int tCK_PrioritaRichiestaField;
        
        private int tCK_TipoChiusuraChiamataFatturaField;
        
        private string oraInzioInterventoField;
        
        private string oraFineInterventoField;
        
        private string nomePersonaRiferimentoField;
        
        private string telPersonaRiferimentoField;
        
        private string mailPersonaRiferimentoField;
        
        private float dirittoFissoField;
        
        private float tariffaOrariaField;
        
        private int speseViaggioKmField;
        
        private float speseViaggioEuroField;
        
        private float totaleEuroForfaitField;
        
        private string tCK_StatusChiamata_etichettaField;
        
        private string tCK_TipoRichiesta_etichettaField;
        
        private string tCK_AreaCompetenza_etichettaField;
        
        private string tCK_TipoEsecuzionePresunta_etichettaField;
        
        private string tCK_TipoEsecuzione_etichettaField;
        
        private string tCK_PrioritaRichiesta_etichettaField;
        
        private string imgFirmaClienteField;
        
        private string imgFirmaTecnicoField;
        
        private string firmaClienteField;
        
        private bool ticketFirmatoField;
        
        private string interventoPressoField;
        
        private string firmaTecnicoField;
        
        private string noteAnnullamentoTckField;
        
        private string noteTecnicoField;
        
        private string linkTckPdfField;
        
        private string tckInviatoAField;
        
        private string tCK_StatusChiamataChiusura_EtichettaField;
        
        private int totTecnici_TCKField;
        
        private float tempoInterventoTotaleField;
        
        private string uM_TempoField;
        
        private int statusControlloFattField;
        
        private string approvatoDaField;
        
        private int statusControlloRegistrazioneField;
        
        private int numeroRegistrazioneField;
        
        private string noteFatturazioneFinaleField;
        
        private int statusControlloFatturazioneFinaleField;
        
        private string societaField;
        
        private string denomField;
        
        private string indField;
        
        private string provField;
        
        private string locField;
        
        private string telField;
        
        private string riferimField;
        
        private string eMailField;
        
        private string codCliField;
        
        private string codArt_KingField;
        
        private int idIntervento_KingField;
        
        private string oggettoTCKField;
        
        private string tecniciField;
        
        private bool assegnatoCalendTecnicoField;
        
        private string inizioInterventoField;
        
        private string fineInterventoField;
        
        private string recurrenceInfoField;
        
        private string resourceIdField;
        
        private string iDExchangeField;
        
        private string tecnicoField;
        
        private int recurrenceEventField;
        
        private bool ticketPadreField;
        
        private string iDRecurrenceField;
        
        private string impiantoField;
        
        private string codiceImpiantoField;
        
        private string dataFineInterventoField;
        
        private bool prioritaCalendarioField;
        
        private string valoreColonnaField;
        
        private bool customerField;
        
        private string allegatiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CodRapportino {
            get {
                return this.codRapportinoField;
            }
            set {
                this.codRapportinoField = value;
                this.RaisePropertyChanged("CodRapportino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CodCliente {
            get {
                return this.codClienteField;
            }
            set {
                this.codClienteField = value;
                this.RaisePropertyChanged("CodCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Società {
            get {
                return this.societàField;
            }
            set {
                this.societàField = value;
                this.RaisePropertyChanged("Società");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PIva {
            get {
                return this.pIvaField;
            }
            set {
                this.pIvaField = value;
                this.RaisePropertyChanged("PIva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Indirizzo {
            get {
                return this.indirizzoField;
            }
            set {
                this.indirizzoField = value;
                this.RaisePropertyChanged("Indirizzo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Cap {
            get {
                return this.capField;
            }
            set {
                this.capField = value;
                this.RaisePropertyChanged("Cap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Località {
            get {
                return this.localitàField;
            }
            set {
                this.localitàField = value;
                this.RaisePropertyChanged("Località");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Provincia {
            get {
                return this.provinciaField;
            }
            set {
                this.provinciaField = value;
                this.RaisePropertyChanged("Provincia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
                this.RaisePropertyChanged("Fax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Matricola {
            get {
                return this.matricolaField;
            }
            set {
                this.matricolaField = value;
                this.RaisePropertyChanged("Matricola");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Scala {
            get {
                return this.scalaField;
            }
            set {
                this.scalaField = value;
                this.RaisePropertyChanged("Scala");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int TipoImpianto {
            get {
                return this.tipoImpiantoField;
            }
            set {
                this.tipoImpiantoField = value;
                this.RaisePropertyChanged("TipoImpianto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string PersonaDaContattare {
            get {
                return this.personaDaContattareField;
            }
            set {
                this.personaDaContattareField = value;
                this.RaisePropertyChanged("PersonaDaContattare");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int TipoChiamata {
            get {
                return this.tipoChiamataField;
            }
            set {
                this.tipoChiamataField = value;
                this.RaisePropertyChanged("TipoChiamata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int AreaAss {
            get {
                return this.areaAssField;
            }
            set {
                this.areaAssField = value;
                this.RaisePropertyChanged("AreaAss");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string MotivoChiamata {
            get {
                return this.motivoChiamataField;
            }
            set {
                this.motivoChiamataField = value;
                this.RaisePropertyChanged("MotivoChiamata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("Note");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string GuastoRilevato {
            get {
                return this.guastoRilevatoField;
            }
            set {
                this.guastoRilevatoField = value;
                this.RaisePropertyChanged("GuastoRilevato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string LavoroEseguito {
            get {
                return this.lavoroEseguitoField;
            }
            set {
                this.lavoroEseguitoField = value;
                this.RaisePropertyChanged("LavoroEseguito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public bool InterventoChiuso {
            get {
                return this.interventoChiusoField;
            }
            set {
                this.interventoChiusoField = value;
                this.RaisePropertyChanged("InterventoChiuso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Osservazioni {
            get {
                return this.osservazioniField;
            }
            set {
                this.osservazioniField = value;
                this.RaisePropertyChanged("Osservazioni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string DataIntervento {
            get {
                return this.dataInterventoField;
            }
            set {
                this.dataInterventoField = value;
                this.RaisePropertyChanged("DataIntervento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string DataIns {
            get {
                return this.dataInsField;
            }
            set {
                this.dataInsField = value;
                this.RaisePropertyChanged("DataIns");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string EditUser {
            get {
                return this.editUserField;
            }
            set {
                this.editUserField = value;
                this.RaisePropertyChanged("EditUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string CreatedOn {
            get {
                return this.createdOnField;
            }
            set {
                this.createdOnField = value;
                this.RaisePropertyChanged("CreatedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string UpdatedOn {
            get {
                return this.updatedOnField;
            }
            set {
                this.updatedOnField = value;
                this.RaisePropertyChanged("UpdatedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("User");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string Ore {
            get {
                return this.oreField;
            }
            set {
                this.oreField = value;
                this.RaisePropertyChanged("Ore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public int StatusRpt {
            get {
                return this.statusRptField;
            }
            set {
                this.statusRptField = value;
                this.RaisePropertyChanged("StatusRpt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string IncaricatoCli {
            get {
                return this.incaricatoCliField;
            }
            set {
                this.incaricatoCliField = value;
                this.RaisePropertyChanged("IncaricatoCli");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string ImmagineTxt {
            get {
                return this.immagineTxtField;
            }
            set {
                this.immagineTxtField = value;
                this.RaisePropertyChanged("ImmagineTxt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string PercorsoImmagine {
            get {
                return this.percorsoImmagineField;
            }
            set {
                this.percorsoImmagineField = value;
                this.RaisePropertyChanged("PercorsoImmagine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public int TCK_TipoRichiesta {
            get {
                return this.tCK_TipoRichiestaField;
            }
            set {
                this.tCK_TipoRichiestaField = value;
                this.RaisePropertyChanged("TCK_TipoRichiesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public int TCK_AreaCompetenza {
            get {
                return this.tCK_AreaCompetenzaField;
            }
            set {
                this.tCK_AreaCompetenzaField = value;
                this.RaisePropertyChanged("TCK_AreaCompetenza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public int TCK_TipoEsecuzionePresunta {
            get {
                return this.tCK_TipoEsecuzionePresuntaField;
            }
            set {
                this.tCK_TipoEsecuzionePresuntaField = value;
                this.RaisePropertyChanged("TCK_TipoEsecuzionePresunta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public int TCK_TipoEsecuzione {
            get {
                return this.tCK_TipoEsecuzioneField;
            }
            set {
                this.tCK_TipoEsecuzioneField = value;
                this.RaisePropertyChanged("TCK_TipoEsecuzione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public int TCK_StatusChiamata {
            get {
                return this.tCK_StatusChiamataField;
            }
            set {
                this.tCK_StatusChiamataField = value;
                this.RaisePropertyChanged("TCK_StatusChiamata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public int TCK_StatusChiamataChiusura {
            get {
                return this.tCK_StatusChiamataChiusuraField;
            }
            set {
                this.tCK_StatusChiamataChiusuraField = value;
                this.RaisePropertyChanged("TCK_StatusChiamataChiusura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public int TCK_PrioritaRichiesta {
            get {
                return this.tCK_PrioritaRichiestaField;
            }
            set {
                this.tCK_PrioritaRichiestaField = value;
                this.RaisePropertyChanged("TCK_PrioritaRichiesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public int TCK_TipoChiusuraChiamataFattura {
            get {
                return this.tCK_TipoChiusuraChiamataFatturaField;
            }
            set {
                this.tCK_TipoChiusuraChiamataFatturaField = value;
                this.RaisePropertyChanged("TCK_TipoChiusuraChiamataFattura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public string OraInzioIntervento {
            get {
                return this.oraInzioInterventoField;
            }
            set {
                this.oraInzioInterventoField = value;
                this.RaisePropertyChanged("OraInzioIntervento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public string OraFineIntervento {
            get {
                return this.oraFineInterventoField;
            }
            set {
                this.oraFineInterventoField = value;
                this.RaisePropertyChanged("OraFineIntervento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string NomePersonaRiferimento {
            get {
                return this.nomePersonaRiferimentoField;
            }
            set {
                this.nomePersonaRiferimentoField = value;
                this.RaisePropertyChanged("NomePersonaRiferimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string TelPersonaRiferimento {
            get {
                return this.telPersonaRiferimentoField;
            }
            set {
                this.telPersonaRiferimentoField = value;
                this.RaisePropertyChanged("TelPersonaRiferimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public string MailPersonaRiferimento {
            get {
                return this.mailPersonaRiferimentoField;
            }
            set {
                this.mailPersonaRiferimentoField = value;
                this.RaisePropertyChanged("MailPersonaRiferimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public float DirittoFisso {
            get {
                return this.dirittoFissoField;
            }
            set {
                this.dirittoFissoField = value;
                this.RaisePropertyChanged("DirittoFisso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public float TariffaOraria {
            get {
                return this.tariffaOrariaField;
            }
            set {
                this.tariffaOrariaField = value;
                this.RaisePropertyChanged("TariffaOraria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public int SpeseViaggioKm {
            get {
                return this.speseViaggioKmField;
            }
            set {
                this.speseViaggioKmField = value;
                this.RaisePropertyChanged("SpeseViaggioKm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public float SpeseViaggioEuro {
            get {
                return this.speseViaggioEuroField;
            }
            set {
                this.speseViaggioEuroField = value;
                this.RaisePropertyChanged("SpeseViaggioEuro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public float TotaleEuroForfait {
            get {
                return this.totaleEuroForfaitField;
            }
            set {
                this.totaleEuroForfaitField = value;
                this.RaisePropertyChanged("TotaleEuroForfait");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public string TCK_StatusChiamata_etichetta {
            get {
                return this.tCK_StatusChiamata_etichettaField;
            }
            set {
                this.tCK_StatusChiamata_etichettaField = value;
                this.RaisePropertyChanged("TCK_StatusChiamata_etichetta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public string TCK_TipoRichiesta_etichetta {
            get {
                return this.tCK_TipoRichiesta_etichettaField;
            }
            set {
                this.tCK_TipoRichiesta_etichettaField = value;
                this.RaisePropertyChanged("TCK_TipoRichiesta_etichetta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=55)]
        public string TCK_AreaCompetenza_etichetta {
            get {
                return this.tCK_AreaCompetenza_etichettaField;
            }
            set {
                this.tCK_AreaCompetenza_etichettaField = value;
                this.RaisePropertyChanged("TCK_AreaCompetenza_etichetta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=56)]
        public string TCK_TipoEsecuzionePresunta_etichetta {
            get {
                return this.tCK_TipoEsecuzionePresunta_etichettaField;
            }
            set {
                this.tCK_TipoEsecuzionePresunta_etichettaField = value;
                this.RaisePropertyChanged("TCK_TipoEsecuzionePresunta_etichetta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=57)]
        public string TCK_TipoEsecuzione_etichetta {
            get {
                return this.tCK_TipoEsecuzione_etichettaField;
            }
            set {
                this.tCK_TipoEsecuzione_etichettaField = value;
                this.RaisePropertyChanged("TCK_TipoEsecuzione_etichetta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=58)]
        public string TCK_PrioritaRichiesta_etichetta {
            get {
                return this.tCK_PrioritaRichiesta_etichettaField;
            }
            set {
                this.tCK_PrioritaRichiesta_etichettaField = value;
                this.RaisePropertyChanged("TCK_PrioritaRichiesta_etichetta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=59)]
        public string ImgFirmaCliente {
            get {
                return this.imgFirmaClienteField;
            }
            set {
                this.imgFirmaClienteField = value;
                this.RaisePropertyChanged("ImgFirmaCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=60)]
        public string ImgFirmaTecnico {
            get {
                return this.imgFirmaTecnicoField;
            }
            set {
                this.imgFirmaTecnicoField = value;
                this.RaisePropertyChanged("ImgFirmaTecnico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=61)]
        public string FirmaCliente {
            get {
                return this.firmaClienteField;
            }
            set {
                this.firmaClienteField = value;
                this.RaisePropertyChanged("FirmaCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=62)]
        public bool TicketFirmato {
            get {
                return this.ticketFirmatoField;
            }
            set {
                this.ticketFirmatoField = value;
                this.RaisePropertyChanged("TicketFirmato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=63)]
        public string InterventoPresso {
            get {
                return this.interventoPressoField;
            }
            set {
                this.interventoPressoField = value;
                this.RaisePropertyChanged("InterventoPresso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=64)]
        public string FirmaTecnico {
            get {
                return this.firmaTecnicoField;
            }
            set {
                this.firmaTecnicoField = value;
                this.RaisePropertyChanged("FirmaTecnico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=65)]
        public string NoteAnnullamentoTck {
            get {
                return this.noteAnnullamentoTckField;
            }
            set {
                this.noteAnnullamentoTckField = value;
                this.RaisePropertyChanged("NoteAnnullamentoTck");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=66)]
        public string NoteTecnico {
            get {
                return this.noteTecnicoField;
            }
            set {
                this.noteTecnicoField = value;
                this.RaisePropertyChanged("NoteTecnico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=67)]
        public string LinkTckPdf {
            get {
                return this.linkTckPdfField;
            }
            set {
                this.linkTckPdfField = value;
                this.RaisePropertyChanged("LinkTckPdf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=68)]
        public string TckInviatoA {
            get {
                return this.tckInviatoAField;
            }
            set {
                this.tckInviatoAField = value;
                this.RaisePropertyChanged("TckInviatoA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=69)]
        public string TCK_StatusChiamataChiusura_Etichetta {
            get {
                return this.tCK_StatusChiamataChiusura_EtichettaField;
            }
            set {
                this.tCK_StatusChiamataChiusura_EtichettaField = value;
                this.RaisePropertyChanged("TCK_StatusChiamataChiusura_Etichetta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=70)]
        public int TotTecnici_TCK {
            get {
                return this.totTecnici_TCKField;
            }
            set {
                this.totTecnici_TCKField = value;
                this.RaisePropertyChanged("TotTecnici_TCK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=71)]
        public float TempoInterventoTotale {
            get {
                return this.tempoInterventoTotaleField;
            }
            set {
                this.tempoInterventoTotaleField = value;
                this.RaisePropertyChanged("TempoInterventoTotale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=72)]
        public string UM_Tempo {
            get {
                return this.uM_TempoField;
            }
            set {
                this.uM_TempoField = value;
                this.RaisePropertyChanged("UM_Tempo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=73)]
        public int StatusControlloFatt {
            get {
                return this.statusControlloFattField;
            }
            set {
                this.statusControlloFattField = value;
                this.RaisePropertyChanged("StatusControlloFatt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=74)]
        public string ApprovatoDa {
            get {
                return this.approvatoDaField;
            }
            set {
                this.approvatoDaField = value;
                this.RaisePropertyChanged("ApprovatoDa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=75)]
        public int StatusControlloRegistrazione {
            get {
                return this.statusControlloRegistrazioneField;
            }
            set {
                this.statusControlloRegistrazioneField = value;
                this.RaisePropertyChanged("StatusControlloRegistrazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=76)]
        public int NumeroRegistrazione {
            get {
                return this.numeroRegistrazioneField;
            }
            set {
                this.numeroRegistrazioneField = value;
                this.RaisePropertyChanged("NumeroRegistrazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=77)]
        public string NoteFatturazioneFinale {
            get {
                return this.noteFatturazioneFinaleField;
            }
            set {
                this.noteFatturazioneFinaleField = value;
                this.RaisePropertyChanged("NoteFatturazioneFinale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=78)]
        public int StatusControlloFatturazioneFinale {
            get {
                return this.statusControlloFatturazioneFinaleField;
            }
            set {
                this.statusControlloFatturazioneFinaleField = value;
                this.RaisePropertyChanged("StatusControlloFatturazioneFinale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=79)]
        public string societa {
            get {
                return this.societaField;
            }
            set {
                this.societaField = value;
                this.RaisePropertyChanged("societa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=80)]
        public string Denom {
            get {
                return this.denomField;
            }
            set {
                this.denomField = value;
                this.RaisePropertyChanged("Denom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=81)]
        public string Ind {
            get {
                return this.indField;
            }
            set {
                this.indField = value;
                this.RaisePropertyChanged("Ind");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=82)]
        public string Prov {
            get {
                return this.provField;
            }
            set {
                this.provField = value;
                this.RaisePropertyChanged("Prov");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=83)]
        public string Loc {
            get {
                return this.locField;
            }
            set {
                this.locField = value;
                this.RaisePropertyChanged("Loc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=84)]
        public string Tel {
            get {
                return this.telField;
            }
            set {
                this.telField = value;
                this.RaisePropertyChanged("Tel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=85)]
        public string Riferim {
            get {
                return this.riferimField;
            }
            set {
                this.riferimField = value;
                this.RaisePropertyChanged("Riferim");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=86)]
        public string EMail {
            get {
                return this.eMailField;
            }
            set {
                this.eMailField = value;
                this.RaisePropertyChanged("EMail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=87)]
        public string CodCli {
            get {
                return this.codCliField;
            }
            set {
                this.codCliField = value;
                this.RaisePropertyChanged("CodCli");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=88)]
        public string CodArt_King {
            get {
                return this.codArt_KingField;
            }
            set {
                this.codArt_KingField = value;
                this.RaisePropertyChanged("CodArt_King");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=89)]
        public int IdIntervento_King {
            get {
                return this.idIntervento_KingField;
            }
            set {
                this.idIntervento_KingField = value;
                this.RaisePropertyChanged("IdIntervento_King");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=90)]
        public string OggettoTCK {
            get {
                return this.oggettoTCKField;
            }
            set {
                this.oggettoTCKField = value;
                this.RaisePropertyChanged("OggettoTCK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=91)]
        public string Tecnici {
            get {
                return this.tecniciField;
            }
            set {
                this.tecniciField = value;
                this.RaisePropertyChanged("Tecnici");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=92)]
        public bool AssegnatoCalendTecnico {
            get {
                return this.assegnatoCalendTecnicoField;
            }
            set {
                this.assegnatoCalendTecnicoField = value;
                this.RaisePropertyChanged("AssegnatoCalendTecnico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=93)]
        public string InizioIntervento {
            get {
                return this.inizioInterventoField;
            }
            set {
                this.inizioInterventoField = value;
                this.RaisePropertyChanged("InizioIntervento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=94)]
        public string FineIntervento {
            get {
                return this.fineInterventoField;
            }
            set {
                this.fineInterventoField = value;
                this.RaisePropertyChanged("FineIntervento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=95)]
        public string RecurrenceInfo {
            get {
                return this.recurrenceInfoField;
            }
            set {
                this.recurrenceInfoField = value;
                this.RaisePropertyChanged("RecurrenceInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=96)]
        public string ResourceId {
            get {
                return this.resourceIdField;
            }
            set {
                this.resourceIdField = value;
                this.RaisePropertyChanged("ResourceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=97)]
        public string IDExchange {
            get {
                return this.iDExchangeField;
            }
            set {
                this.iDExchangeField = value;
                this.RaisePropertyChanged("IDExchange");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=98)]
        public string Tecnico {
            get {
                return this.tecnicoField;
            }
            set {
                this.tecnicoField = value;
                this.RaisePropertyChanged("Tecnico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=99)]
        public int RecurrenceEvent {
            get {
                return this.recurrenceEventField;
            }
            set {
                this.recurrenceEventField = value;
                this.RaisePropertyChanged("RecurrenceEvent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=100)]
        public bool TicketPadre {
            get {
                return this.ticketPadreField;
            }
            set {
                this.ticketPadreField = value;
                this.RaisePropertyChanged("TicketPadre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=101)]
        public string IDRecurrence {
            get {
                return this.iDRecurrenceField;
            }
            set {
                this.iDRecurrenceField = value;
                this.RaisePropertyChanged("IDRecurrence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=102)]
        public string Impianto {
            get {
                return this.impiantoField;
            }
            set {
                this.impiantoField = value;
                this.RaisePropertyChanged("Impianto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=103)]
        public string CodiceImpianto {
            get {
                return this.codiceImpiantoField;
            }
            set {
                this.codiceImpiantoField = value;
                this.RaisePropertyChanged("CodiceImpianto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=104)]
        public string DataFineIntervento {
            get {
                return this.dataFineInterventoField;
            }
            set {
                this.dataFineInterventoField = value;
                this.RaisePropertyChanged("DataFineIntervento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=105)]
        public bool PrioritaCalendario {
            get {
                return this.prioritaCalendarioField;
            }
            set {
                this.prioritaCalendarioField = value;
                this.RaisePropertyChanged("PrioritaCalendario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=106)]
        public string ValoreColonna {
            get {
                return this.valoreColonnaField;
            }
            set {
                this.valoreColonnaField = value;
                this.RaisePropertyChanged("ValoreColonna");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=107)]
        public bool Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
                this.RaisePropertyChanged("Customer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=108)]
        public string Allegati {
            get {
                return this.allegatiField;
            }
            set {
                this.allegatiField = value;
                this.RaisePropertyChanged("Allegati");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService_primoSoapChannel : INTRA.Webservice_primo_online.WebService_primoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService_primoSoapClient : System.ServiceModel.ClientBase<INTRA.Webservice_primo_online.WebService_primoSoap>, INTRA.Webservice_primo_online.WebService_primoSoap {
        
        public WebService_primoSoapClient() {
        }
        
        public WebService_primoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService_primoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_primoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_primoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public int converttodaysweb(int day, int month, int year) {
            return base.Channel.converttodaysweb(day, month, year);
        }
        
        public System.Threading.Tasks.Task<int> converttodayswebAsync(int day, int month, int year) {
            return base.Channel.converttodayswebAsync(day, month, year);
        }
        
        public int Multiplication(int a, int b) {
            return base.Channel.Multiplication(a, b);
        }
        
        public System.Threading.Tasks.Task<int> MultiplicationAsync(int a, int b) {
            return base.Channel.MultiplicationAsync(a, b);
        }
        
        public int addTckCustomer(string CodCli, string OggettoTCK, string MotivoChiamata, int TCK_TipoRichiesta, int TCK_AreaCompetenza, int TCK_StatusChiamata, int TCK_PrioritaRichiesta, string NomePersonaRiferimento, string TelPersonaRiferimento, string MailPersonaRiferimento, string UserName) {
            return base.Channel.addTckCustomer(CodCli, OggettoTCK, MotivoChiamata, TCK_TipoRichiesta, TCK_AreaCompetenza, TCK_StatusChiamata, TCK_PrioritaRichiesta, NomePersonaRiferimento, TelPersonaRiferimento, MailPersonaRiferimento, UserName);
        }
        
        public System.Threading.Tasks.Task<int> addTckCustomerAsync(string CodCli, string OggettoTCK, string MotivoChiamata, int TCK_TipoRichiesta, int TCK_AreaCompetenza, int TCK_StatusChiamata, int TCK_PrioritaRichiesta, string NomePersonaRiferimento, string TelPersonaRiferimento, string MailPersonaRiferimento, string UserName) {
            return base.Channel.addTckCustomerAsync(CodCli, OggettoTCK, MotivoChiamata, TCK_TipoRichiesta, TCK_AreaCompetenza, TCK_StatusChiamata, TCK_PrioritaRichiesta, NomePersonaRiferimento, TelPersonaRiferimento, MailPersonaRiferimento, UserName);
        }
        
        public int addTckCustomerArray(INTRA.Webservice_primo_online.TCK_Ticket_WS TckPost, string SessionID) {
            return base.Channel.addTckCustomerArray(TckPost, SessionID);
        }
        
        public System.Threading.Tasks.Task<int> addTckCustomerArrayAsync(INTRA.Webservice_primo_online.TCK_Ticket_WS TckPost, string SessionID) {
            return base.Channel.addTckCustomerArrayAsync(TckPost, SessionID);
        }
        
        public void SendMailAimXtype(string from, string to, int CodRapportino, int TicketStatus_Template, string UserCrudTemplate, string MailTecnicoTemplate, string NomeTecnicoTemplate, int Attachments) {
            base.Channel.SendMailAimXtype(from, to, CodRapportino, TicketStatus_Template, UserCrudTemplate, MailTecnicoTemplate, NomeTecnicoTemplate, Attachments);
        }
        
        public System.Threading.Tasks.Task SendMailAimXtypeAsync(string from, string to, int CodRapportino, int TicketStatus_Template, string UserCrudTemplate, string MailTecnicoTemplate, string NomeTecnicoTemplate, int Attachments) {
            return base.Channel.SendMailAimXtypeAsync(from, to, CodRapportino, TicketStatus_Template, UserCrudTemplate, MailTecnicoTemplate, NomeTecnicoTemplate, Attachments);
        }
        
        public void SendTicketMailAim(int TicketId, int TicketStatus, string UserCrud, INTRA.Webservice_primo_online.TCK_Ticket_WS rapportini, string MailTecnico, string NomeTecnico, bool Responsabili, string TipoAllegato, string IdAllegato) {
            base.Channel.SendTicketMailAim(TicketId, TicketStatus, UserCrud, rapportini, MailTecnico, NomeTecnico, Responsabili, TipoAllegato, IdAllegato);
        }
        
        public System.Threading.Tasks.Task SendTicketMailAimAsync(int TicketId, int TicketStatus, string UserCrud, INTRA.Webservice_primo_online.TCK_Ticket_WS rapportini, string MailTecnico, string NomeTecnico, bool Responsabili, string TipoAllegato, string IdAllegato) {
            return base.Channel.SendTicketMailAimAsync(TicketId, TicketStatus, UserCrud, rapportini, MailTecnico, NomeTecnico, Responsabili, TipoAllegato, IdAllegato);
        }
        
        public void TestSendEmai(string from, string to, string msg, string msgObject) {
            base.Channel.TestSendEmai(from, to, msg, msgObject);
        }
        
        public System.Threading.Tasks.Task TestSendEmaiAsync(string from, string to, string msg, string msgObject) {
            return base.Channel.TestSendEmaiAsync(from, to, msg, msgObject);
        }
        
        public string CheckHostStatus(string hostCodParam, string userNameCodParam, string passwordCodParam, string portCodParam, string SslModeCodParam, string EnableImplicitSslCodParam) {
            return base.Channel.CheckHostStatus(hostCodParam, userNameCodParam, passwordCodParam, portCodParam, SslModeCodParam, EnableImplicitSslCodParam);
        }
        
        public System.Threading.Tasks.Task<string> CheckHostStatusAsync(string hostCodParam, string userNameCodParam, string passwordCodParam, string portCodParam, string SslModeCodParam, string EnableImplicitSslCodParam) {
            return base.Channel.CheckHostStatusAsync(hostCodParam, userNameCodParam, passwordCodParam, portCodParam, SslModeCodParam, EnableImplicitSslCodParam);
        }
        
        public void UpdateNoteTecnico(int idTicket, string nota) {
            base.Channel.UpdateNoteTecnico(idTicket, nota);
        }
        
        public System.Threading.Tasks.Task UpdateNoteTecnicoAsync(int idTicket, string nota) {
            return base.Channel.UpdateNoteTecnicoAsync(idTicket, nota);
        }
        
        public void UpdateStatusChiamata(int idTicket, int status) {
            base.Channel.UpdateStatusChiamata(idTicket, status);
        }
        
        public System.Threading.Tasks.Task UpdateStatusChiamataAsync(int idTicket, int status) {
            return base.Channel.UpdateStatusChiamataAsync(idTicket, status);
        }
    }
}
