//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Contratto_Riepilogo_Det_Rpt {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Contratto_Riepilogo_Det_Rpt() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache usata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Contratto_Riepilogo_Det_Rpt", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite con questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a  SELECT DISTINCT 
        ///                         TCK_TestataTicket.DataIntervento, TCK_TestataTicket.CodRapportino, TCK_TestataTicket.CodCli, TCK_TestataTicket.IDContrattoAssistenza, TCK_TestataTicket.TCK_TipoChiusuraChiamataFattura, TCK_TestataTicket.UM, 
        ///                         TCK_TestataTicket.TotTecnici, TCK_TecniciVsTicket_View.NameValues AS Utente, TCK_TestataTicket.LavoroEseguito, TCK_TestataTicket.TempoInterventoTotale, TCK_TestataTicket.StatusCotrolloFatt, 
        ///                         TCK_AreaCompetenza [stringa troncata]&quot;;.
        /// </summary>
        internal static string customSqlQuery1_Sql {
            get {
                return ResourceManager.GetString("customSqlQuery1.Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a  PERhdGFTZXQgTmFtZT0ic3FsRGF0YVNvdXJjZTEiPjxWaWV3IE5hbWU9IlF1ZXJ5Ij48RmllbGQgTmFtZT0iRGF0YUludGVydmVudG8iIFR5cGU9IkRhdGVUaW1lIiAvPjxGaWVsZCBOYW1lPSJDb2RSYXBwb3J0aW5vIiBUeXBlPSJJbnQzMiIgLz48RmllbGQgTmFtZT0iQ29kQ2xpIiBUeXBlPSJTdHJpbmciIC8+PEZpZWxkIE5hbWU9IklEQ29udHJhdHRvQXNzaXN0ZW56YSIgVHlwZT0iU3RyaW5nIiAvPjxGaWVsZCBOYW1lPSJUQ0tfVGlwb0NoaXVzdXJhQ2hpYW1hdGFGYXR0dXJhIiBUeXBlPSJJbnQzMiIgLz48RmllbGQgTmFtZT0iVU0iIFR5cGU9IlN0cmluZyIgLz48RmllbGQgTmFtZT0iVG90VGVjbmljaSIgVHlwZT0iSW50MzIiIC8+PEZpZWxkIE5hbWU9IlV0ZW50ZSIg [stringa troncata]&quot;;.
        /// </summary>
        internal static string sqlDataSource1_ResultSchemaSerializable {
            get {
                return ResourceManager.GetString("sqlDataSource1.ResultSchemaSerializable", resourceCulture);
            }
        }
    }
}
