//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Contratto_Riepilogo_Rpt {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Contratto_Riepilogo_Rpt() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache usata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Contratto_Riepilogo_Rpt", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite con questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a  select &quot;U_Carnet_Contratti_View_Intra&quot;.&quot;ContM&quot;,
        ///       &quot;U_Carnet_Contratti_View_Intra&quot;.&quot;CodCli&quot;,
        ///       &quot;U_Carnet_Contratti_View_Intra&quot;.&quot;Denom&quot;,
        ///       &quot;U_Carnet_Contratti_View_Intra&quot;.&quot;U_Carnet&quot;,
        ///       &quot;U_Carnet_Contratti_View_Intra&quot;.&quot;U_ContrattoHWSW&quot;,
        ///       &quot;U_Carnet_Contratti_View_Intra&quot;.&quot;U_Print&quot;,
        ///       &quot;U_Carnet_Contratti_View_Intra&quot;.&quot;IdProdotto&quot;,
        ///       &quot;U_Carnet_Contratti_View_Intra&quot;.&quot;U_TotOreContratto&quot;,
        ///       &quot;U_Carnet_Contratti_View_Intra&quot;.&quot;U_CC&quot;,
        ///       &quot;U_Carnet_Contratti_View_Intra&quot;. [stringa troncata]&quot;;.
        /// </summary>
        internal static string customSqlQuery1_Sql {
            get {
                return ResourceManager.GetString("customSqlQuery1.Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a  PERhdGFTZXQgTmFtZT0ic3FsRGF0YVNvdXJjZTEiPjxWaWV3IE5hbWU9IlVfQ2FybmV0X0NvbnRyYXR0aV9WaWV3X0ludHJhIj48RmllbGQgTmFtZT0iQ29udE0iIFR5cGU9IkludDMyIiAvPjxGaWVsZCBOYW1lPSJDb2RDbGkiIFR5cGU9IlN0cmluZyIgLz48RmllbGQgTmFtZT0iRGVub20iIFR5cGU9IlN0cmluZyIgLz48RmllbGQgTmFtZT0iVV9DYXJuZXQiIFR5cGU9IkJvb2xlYW4iIC8+PEZpZWxkIE5hbWU9IlVfQ29udHJhdHRvSFdTVyIgVHlwZT0iQm9vbGVhbiIgLz48RmllbGQgTmFtZT0iVV9QcmludCIgVHlwZT0iQm9vbGVhbiIgLz48RmllbGQgTmFtZT0iSWRQcm9kb3R0byIgVHlwZT0iU3RyaW5nIiAvPjxGaWVsZCBOYW1lPSJVX1RvdE9yZUNvbnRyYXR0byIgVHlw [stringa troncata]&quot;;.
        /// </summary>
        internal static string sqlDataSource1_ResultSchemaSerializable {
            get {
                return ResourceManager.GetString("sqlDataSource1.ResultSchemaSerializable", resourceCulture);
            }
        }
    }
}
