#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTRA.AppCode
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="info4u_V2.0.2_")]
	public partial class ListaTicket_LINQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definizioni metodo Extensibility
    partial void OnCreated();
    partial void InsertListaTicket_View(ListaTicket_View instance);
    partial void UpdateListaTicket_View(ListaTicket_View instance);
    partial void DeleteListaTicket_View(ListaTicket_View instance);
    #endregion
		
		public ListaTicket_LINQDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["info4portaleConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ListaTicket_LINQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ListaTicket_LINQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ListaTicket_LINQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ListaTicket_LINQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ListaTicket_View> ListaTicket_View
		{
			get
			{
				return this.GetTable<ListaTicket_View>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ListaTicket_View")]
	public partial class ListaTicket_View : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _idStatus;
		
		private string _Indirizzo;
		
		private System.Nullable<System.DateTime> _DataIns;
		
		private string _Cap;
		
		private string _Località;
		
		private string _Provincia;
		
		private System.Nullable<int> _Id;
		
		private string _TipoChiamata;
		
		private string _Colore;
		
		private System.Nullable<int> _CodRapportino;
		
		private string _Società;
		
		private System.Nullable<int> _IdAreaAss;
		
		private string _AreaAss;
		
		private string _ColoreArea;
		
		private string _PrioritaDescr;
		
		private string _PrioritaColore;
		
		private string _TipoEsecDescr;
		
		private string _TipoEsecColore;
		
		private string _MotivoChiamata;
		
		private string _Tecnico;
		
		private string _StatusControlloRegistrazione;
		
		private string _StatusControlloFatturazioneFinale;
		
		private System.Nullable<int> _TCK_StatusChiamata;
		
		private string _LabelClass;
		
		private string _Descrizione;
		
		private System.Nullable<int> _TCK_AreaCompetenza;
		
		private System.Nullable<int> _TCK_TipoRichiesta;
		
		private System.Nullable<int> _TCK_PrioritaRichiesta;
		
		private string _Note;
		
		private string _NoteTecnico;
		
		private string _InsertUser;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidStatusChanging(System.Nullable<int> value);
    partial void OnidStatusChanged();
    partial void OnIndirizzoChanging(string value);
    partial void OnIndirizzoChanged();
    partial void OnDataInsChanging(System.Nullable<System.DateTime> value);
    partial void OnDataInsChanged();
    partial void OnCapChanging(string value);
    partial void OnCapChanged();
    partial void OnLocalitàChanging(string value);
    partial void OnLocalitàChanged();
    partial void OnProvinciaChanging(string value);
    partial void OnProvinciaChanged();
    partial void OnIdChanging(System.Nullable<int> value);
    partial void OnIdChanged();
    partial void OnTipoChiamataChanging(string value);
    partial void OnTipoChiamataChanged();
    partial void OnColoreChanging(string value);
    partial void OnColoreChanged();
    partial void OnCodRapportinoChanging(System.Nullable<int> value);
    partial void OnCodRapportinoChanged();
    partial void OnSocietàChanging(string value);
    partial void OnSocietàChanged();
    partial void OnIdAreaAssChanging(System.Nullable<int> value);
    partial void OnIdAreaAssChanged();
    partial void OnAreaAssChanging(string value);
    partial void OnAreaAssChanged();
    partial void OnColoreAreaChanging(string value);
    partial void OnColoreAreaChanged();
    partial void OnPrioritaDescrChanging(string value);
    partial void OnPrioritaDescrChanged();
    partial void OnPrioritaColoreChanging(string value);
    partial void OnPrioritaColoreChanged();
    partial void OnTipoEsecDescrChanging(string value);
    partial void OnTipoEsecDescrChanged();
    partial void OnTipoEsecColoreChanging(string value);
    partial void OnTipoEsecColoreChanged();
    partial void OnMotivoChiamataChanging(string value);
    partial void OnMotivoChiamataChanged();
    partial void OnTecnicoChanging(string value);
    partial void OnTecnicoChanged();
    partial void OnStatusControlloRegistrazioneChanging(string value);
    partial void OnStatusControlloRegistrazioneChanged();
    partial void OnStatusControlloFatturazioneFinaleChanging(string value);
    partial void OnStatusControlloFatturazioneFinaleChanged();
    partial void OnTCK_StatusChiamataChanging(System.Nullable<int> value);
    partial void OnTCK_StatusChiamataChanged();
    partial void OnLabelClassChanging(string value);
    partial void OnLabelClassChanged();
    partial void OnDescrizioneChanging(string value);
    partial void OnDescrizioneChanged();
    partial void OnTCK_AreaCompetenzaChanging(System.Nullable<int> value);
    partial void OnTCK_AreaCompetenzaChanged();
    partial void OnTCK_TipoRichiestaChanging(System.Nullable<int> value);
    partial void OnTCK_TipoRichiestaChanged();
    partial void OnTCK_PrioritaRichiestaChanging(System.Nullable<int> value);
    partial void OnTCK_PrioritaRichiestaChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnNoteTecnicoChanging(string value);
    partial void OnNoteTecnicoChanged();
    partial void OnInsertUserChanging(string value);
    partial void OnInsertUserChanged();
    #endregion
		
		public ListaTicket_View()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idStatus", DbType="Int")]
		public System.Nullable<int> idStatus
		{
			get
			{
				return this._idStatus;
			}
			set
			{
				if ((this._idStatus != value))
				{
					this.OnidStatusChanging(value);
					this.SendPropertyChanging();
					this._idStatus = value;
					this.SendPropertyChanged("idStatus");
					this.OnidStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Indirizzo", DbType="NVarChar(MAX)")]
		public string Indirizzo
		{
			get
			{
				return this._Indirizzo;
			}
			set
			{
				if ((this._Indirizzo != value))
				{
					this.OnIndirizzoChanging(value);
					this.SendPropertyChanging();
					this._Indirizzo = value;
					this.SendPropertyChanged("Indirizzo");
					this.OnIndirizzoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataIns", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataIns
		{
			get
			{
				return this._DataIns;
			}
			set
			{
				if ((this._DataIns != value))
				{
					this.OnDataInsChanging(value);
					this.SendPropertyChanging();
					this._DataIns = value;
					this.SendPropertyChanged("DataIns");
					this.OnDataInsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cap", DbType="NVarChar(MAX)")]
		public string Cap
		{
			get
			{
				return this._Cap;
			}
			set
			{
				if ((this._Cap != value))
				{
					this.OnCapChanging(value);
					this.SendPropertyChanging();
					this._Cap = value;
					this.SendPropertyChanged("Cap");
					this.OnCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Località", DbType="NVarChar(MAX)")]
		public string Località
		{
			get
			{
				return this._Località;
			}
			set
			{
				if ((this._Località != value))
				{
					this.OnLocalitàChanging(value);
					this.SendPropertyChanging();
					this._Località = value;
					this.SendPropertyChanged("Località");
					this.OnLocalitàChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Provincia", DbType="NVarChar(MAX)")]
		public string Provincia
		{
			get
			{
				return this._Provincia;
			}
			set
			{
				if ((this._Provincia != value))
				{
					this.OnProvinciaChanging(value);
					this.SendPropertyChanging();
					this._Provincia = value;
					this.SendPropertyChanged("Provincia");
					this.OnProvinciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int")]
		public System.Nullable<int> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoChiamata", DbType="NVarChar(100)")]
		public string TipoChiamata
		{
			get
			{
				return this._TipoChiamata;
			}
			set
			{
				if ((this._TipoChiamata != value))
				{
					this.OnTipoChiamataChanging(value);
					this.SendPropertyChanging();
					this._TipoChiamata = value;
					this.SendPropertyChanged("TipoChiamata");
					this.OnTipoChiamataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Colore", DbType="NVarChar(50)")]
		public string Colore
		{
			get
			{
				return this._Colore;
			}
			set
			{
				if ((this._Colore != value))
				{
					this.OnColoreChanging(value);
					this.SendPropertyChanging();
					this._Colore = value;
					this.SendPropertyChanged("Colore");
					this.OnColoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodRapportino", DbType="Int", IsPrimaryKey=true)]
		public System.Nullable<int> CodRapportino
		{
			get
			{
				return this._CodRapportino;
			}
			set
			{
				if ((this._CodRapportino != value))
				{
					this.OnCodRapportinoChanging(value);
					this.SendPropertyChanging();
					this._CodRapportino = value;
					this.SendPropertyChanged("CodRapportino");
					this.OnCodRapportinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Società", DbType="NVarChar(200)")]
		public string Società
		{
			get
			{
				return this._Società;
			}
			set
			{
				if ((this._Società != value))
				{
					this.OnSocietàChanging(value);
					this.SendPropertyChanging();
					this._Società = value;
					this.SendPropertyChanged("Società");
					this.OnSocietàChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAreaAss", DbType="Int")]
		public System.Nullable<int> IdAreaAss
		{
			get
			{
				return this._IdAreaAss;
			}
			set
			{
				if ((this._IdAreaAss != value))
				{
					this.OnIdAreaAssChanging(value);
					this.SendPropertyChanging();
					this._IdAreaAss = value;
					this.SendPropertyChanged("IdAreaAss");
					this.OnIdAreaAssChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AreaAss", DbType="NVarChar(100)")]
		public string AreaAss
		{
			get
			{
				return this._AreaAss;
			}
			set
			{
				if ((this._AreaAss != value))
				{
					this.OnAreaAssChanging(value);
					this.SendPropertyChanging();
					this._AreaAss = value;
					this.SendPropertyChanged("AreaAss");
					this.OnAreaAssChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColoreArea", DbType="NVarChar(50)")]
		public string ColoreArea
		{
			get
			{
				return this._ColoreArea;
			}
			set
			{
				if ((this._ColoreArea != value))
				{
					this.OnColoreAreaChanging(value);
					this.SendPropertyChanging();
					this._ColoreArea = value;
					this.SendPropertyChanged("ColoreArea");
					this.OnColoreAreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrioritaDescr", DbType="NVarChar(100)")]
		public string PrioritaDescr
		{
			get
			{
				return this._PrioritaDescr;
			}
			set
			{
				if ((this._PrioritaDescr != value))
				{
					this.OnPrioritaDescrChanging(value);
					this.SendPropertyChanging();
					this._PrioritaDescr = value;
					this.SendPropertyChanged("PrioritaDescr");
					this.OnPrioritaDescrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrioritaColore", DbType="NVarChar(50)")]
		public string PrioritaColore
		{
			get
			{
				return this._PrioritaColore;
			}
			set
			{
				if ((this._PrioritaColore != value))
				{
					this.OnPrioritaColoreChanging(value);
					this.SendPropertyChanging();
					this._PrioritaColore = value;
					this.SendPropertyChanged("PrioritaColore");
					this.OnPrioritaColoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoEsecDescr", DbType="NVarChar(100)")]
		public string TipoEsecDescr
		{
			get
			{
				return this._TipoEsecDescr;
			}
			set
			{
				if ((this._TipoEsecDescr != value))
				{
					this.OnTipoEsecDescrChanging(value);
					this.SendPropertyChanging();
					this._TipoEsecDescr = value;
					this.SendPropertyChanged("TipoEsecDescr");
					this.OnTipoEsecDescrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoEsecColore", DbType="NVarChar(50)")]
		public string TipoEsecColore
		{
			get
			{
				return this._TipoEsecColore;
			}
			set
			{
				if ((this._TipoEsecColore != value))
				{
					this.OnTipoEsecColoreChanging(value);
					this.SendPropertyChanging();
					this._TipoEsecColore = value;
					this.SendPropertyChanged("TipoEsecColore");
					this.OnTipoEsecColoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotivoChiamata", DbType="NVarChar(MAX)")]
		public string MotivoChiamata
		{
			get
			{
				return this._MotivoChiamata;
			}
			set
			{
				if ((this._MotivoChiamata != value))
				{
					this.OnMotivoChiamataChanging(value);
					this.SendPropertyChanging();
					this._MotivoChiamata = value;
					this.SendPropertyChanged("MotivoChiamata");
					this.OnMotivoChiamataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tecnico", DbType="VarChar(MAX)")]
		public string Tecnico
		{
			get
			{
				return this._Tecnico;
			}
			set
			{
				if ((this._Tecnico != value))
				{
					this.OnTecnicoChanging(value);
					this.SendPropertyChanging();
					this._Tecnico = value;
					this.SendPropertyChanged("Tecnico");
					this.OnTecnicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusControlloRegistrazione", DbType="NChar(40)")]
		public string StatusControlloRegistrazione
		{
			get
			{
				return this._StatusControlloRegistrazione;
			}
			set
			{
				if ((this._StatusControlloRegistrazione != value))
				{
					this.OnStatusControlloRegistrazioneChanging(value);
					this.SendPropertyChanging();
					this._StatusControlloRegistrazione = value;
					this.SendPropertyChanged("StatusControlloRegistrazione");
					this.OnStatusControlloRegistrazioneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusControlloFatturazioneFinale", DbType="NVarChar(100)")]
		public string StatusControlloFatturazioneFinale
		{
			get
			{
				return this._StatusControlloFatturazioneFinale;
			}
			set
			{
				if ((this._StatusControlloFatturazioneFinale != value))
				{
					this.OnStatusControlloFatturazioneFinaleChanging(value);
					this.SendPropertyChanging();
					this._StatusControlloFatturazioneFinale = value;
					this.SendPropertyChanged("StatusControlloFatturazioneFinale");
					this.OnStatusControlloFatturazioneFinaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCK_StatusChiamata", DbType="Int")]
		public System.Nullable<int> TCK_StatusChiamata
		{
			get
			{
				return this._TCK_StatusChiamata;
			}
			set
			{
				if ((this._TCK_StatusChiamata != value))
				{
					this.OnTCK_StatusChiamataChanging(value);
					this.SendPropertyChanging();
					this._TCK_StatusChiamata = value;
					this.SendPropertyChanged("TCK_StatusChiamata");
					this.OnTCK_StatusChiamataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LabelClass", DbType="NVarChar(50)")]
		public string LabelClass
		{
			get
			{
				return this._LabelClass;
			}
			set
			{
				if ((this._LabelClass != value))
				{
					this.OnLabelClassChanging(value);
					this.SendPropertyChanging();
					this._LabelClass = value;
					this.SendPropertyChanged("LabelClass");
					this.OnLabelClassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descrizione", DbType="NVarChar(100)")]
		public string Descrizione
		{
			get
			{
				return this._Descrizione;
			}
			set
			{
				if ((this._Descrizione != value))
				{
					this.OnDescrizioneChanging(value);
					this.SendPropertyChanging();
					this._Descrizione = value;
					this.SendPropertyChanged("Descrizione");
					this.OnDescrizioneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCK_AreaCompetenza", DbType="Int")]
		public System.Nullable<int> TCK_AreaCompetenza
		{
			get
			{
				return this._TCK_AreaCompetenza;
			}
			set
			{
				if ((this._TCK_AreaCompetenza != value))
				{
					this.OnTCK_AreaCompetenzaChanging(value);
					this.SendPropertyChanging();
					this._TCK_AreaCompetenza = value;
					this.SendPropertyChanged("TCK_AreaCompetenza");
					this.OnTCK_AreaCompetenzaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCK_TipoRichiesta", DbType="Int")]
		public System.Nullable<int> TCK_TipoRichiesta
		{
			get
			{
				return this._TCK_TipoRichiesta;
			}
			set
			{
				if ((this._TCK_TipoRichiesta != value))
				{
					this.OnTCK_TipoRichiestaChanging(value);
					this.SendPropertyChanging();
					this._TCK_TipoRichiesta = value;
					this.SendPropertyChanged("TCK_TipoRichiesta");
					this.OnTCK_TipoRichiestaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCK_PrioritaRichiesta", DbType="Int")]
		public System.Nullable<int> TCK_PrioritaRichiesta
		{
			get
			{
				return this._TCK_PrioritaRichiesta;
			}
			set
			{
				if ((this._TCK_PrioritaRichiesta != value))
				{
					this.OnTCK_PrioritaRichiestaChanging(value);
					this.SendPropertyChanging();
					this._TCK_PrioritaRichiesta = value;
					this.SendPropertyChanged("TCK_PrioritaRichiesta");
					this.OnTCK_PrioritaRichiestaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="nvarchar(max)", CanBeNull=false)]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoteTecnico", DbType="nvarchar(max)", CanBeNull=false)]
		public string NoteTecnico
		{
			get
			{
				return this._NoteTecnico;
			}
			set
			{
				if ((this._NoteTecnico != value))
				{
					this.OnNoteTecnicoChanging(value);
					this.SendPropertyChanging();
					this._NoteTecnico = value;
					this.SendPropertyChanged("NoteTecnico");
					this.OnNoteTecnicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertUser", DbType="nvarchar(200)", CanBeNull=false)]
		public string InsertUser
		{
			get
			{
				return this._InsertUser;
			}
			set
			{
				if ((this._InsertUser != value))
				{
					this.OnInsertUserChanging(value);
					this.SendPropertyChanging();
					this._InsertUser = value;
					this.SendPropertyChanged("InsertUser");
					this.OnInsertUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
