//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace INTRA.WebReference4u {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService_primoSoap", Namespace="http://tempuri.org/")]
    public partial class WebService_primo : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback converttodayswebOperationCompleted;
        
        private System.Threading.SendOrPostCallback MultiplicationOperationCompleted;
        
        private System.Threading.SendOrPostCallback addTckCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback addTckCustomerArrayOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMailAimXtypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMailDBTemplateOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendTicketMailAimOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendTicketMailAim1OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService_primo() {
            this.Url = global::INTRA.Properties.Settings.Default.INTRA_WebReference4u_WebService_primo;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event converttodayswebCompletedEventHandler converttodayswebCompleted;
        
        /// <remarks/>
        public event MultiplicationCompletedEventHandler MultiplicationCompleted;
        
        /// <remarks/>
        public event addTckCustomerCompletedEventHandler addTckCustomerCompleted;
        
        /// <remarks/>
        public event addTckCustomerArrayCompletedEventHandler addTckCustomerArrayCompleted;
        
        /// <remarks/>
        public event SendMailAimXtypeCompletedEventHandler SendMailAimXtypeCompleted;
        
        /// <remarks/>
        public event SendMailDBTemplateCompletedEventHandler SendMailDBTemplateCompleted;
        
        /// <remarks/>
        public event SendTicketMailAimCompletedEventHandler SendTicketMailAimCompleted;
        
        /// <remarks/>
        public event SendTicketMailAim1CompletedEventHandler SendTicketMailAim1Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/converttodaysweb", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int converttodaysweb(int day, int month, int year) {
            object[] results = this.Invoke("converttodaysweb", new object[] {
                        day,
                        month,
                        year});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void converttodayswebAsync(int day, int month, int year) {
            this.converttodayswebAsync(day, month, year, null);
        }
        
        /// <remarks/>
        public void converttodayswebAsync(int day, int month, int year, object userState) {
            if ((this.converttodayswebOperationCompleted == null)) {
                this.converttodayswebOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconverttodayswebOperationCompleted);
            }
            this.InvokeAsync("converttodaysweb", new object[] {
                        day,
                        month,
                        year}, this.converttodayswebOperationCompleted, userState);
        }
        
        private void OnconverttodayswebOperationCompleted(object arg) {
            if ((this.converttodayswebCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.converttodayswebCompleted(this, new converttodayswebCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Multiplication", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Multiplication(int a, int b) {
            object[] results = this.Invoke("Multiplication", new object[] {
                        a,
                        b});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void MultiplicationAsync(int a, int b) {
            this.MultiplicationAsync(a, b, null);
        }
        
        /// <remarks/>
        public void MultiplicationAsync(int a, int b, object userState) {
            if ((this.MultiplicationOperationCompleted == null)) {
                this.MultiplicationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMultiplicationOperationCompleted);
            }
            this.InvokeAsync("Multiplication", new object[] {
                        a,
                        b}, this.MultiplicationOperationCompleted, userState);
        }
        
        private void OnMultiplicationOperationCompleted(object arg) {
            if ((this.MultiplicationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MultiplicationCompleted(this, new MultiplicationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addTckCustomer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int addTckCustomer(string CodCli, string OggettoTCK, string MotivoChiamata, int TCK_TipoRichiesta, int TCK_AreaCompetenza, int TCK_StatusChiamata, int TCK_PrioritaRichiesta, string NomePersonaRiferimento, string TelPersonaRiferimento, string MailPersonaRiferimento, string UserName) {
            object[] results = this.Invoke("addTckCustomer", new object[] {
                        CodCli,
                        OggettoTCK,
                        MotivoChiamata,
                        TCK_TipoRichiesta,
                        TCK_AreaCompetenza,
                        TCK_StatusChiamata,
                        TCK_PrioritaRichiesta,
                        NomePersonaRiferimento,
                        TelPersonaRiferimento,
                        MailPersonaRiferimento,
                        UserName});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void addTckCustomerAsync(string CodCli, string OggettoTCK, string MotivoChiamata, int TCK_TipoRichiesta, int TCK_AreaCompetenza, int TCK_StatusChiamata, int TCK_PrioritaRichiesta, string NomePersonaRiferimento, string TelPersonaRiferimento, string MailPersonaRiferimento, string UserName) {
            this.addTckCustomerAsync(CodCli, OggettoTCK, MotivoChiamata, TCK_TipoRichiesta, TCK_AreaCompetenza, TCK_StatusChiamata, TCK_PrioritaRichiesta, NomePersonaRiferimento, TelPersonaRiferimento, MailPersonaRiferimento, UserName, null);
        }
        
        /// <remarks/>
        public void addTckCustomerAsync(string CodCli, string OggettoTCK, string MotivoChiamata, int TCK_TipoRichiesta, int TCK_AreaCompetenza, int TCK_StatusChiamata, int TCK_PrioritaRichiesta, string NomePersonaRiferimento, string TelPersonaRiferimento, string MailPersonaRiferimento, string UserName, object userState) {
            if ((this.addTckCustomerOperationCompleted == null)) {
                this.addTckCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddTckCustomerOperationCompleted);
            }
            this.InvokeAsync("addTckCustomer", new object[] {
                        CodCli,
                        OggettoTCK,
                        MotivoChiamata,
                        TCK_TipoRichiesta,
                        TCK_AreaCompetenza,
                        TCK_StatusChiamata,
                        TCK_PrioritaRichiesta,
                        NomePersonaRiferimento,
                        TelPersonaRiferimento,
                        MailPersonaRiferimento,
                        UserName}, this.addTckCustomerOperationCompleted, userState);
        }
        
        private void OnaddTckCustomerOperationCompleted(object arg) {
            if ((this.addTckCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addTckCustomerCompleted(this, new addTckCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addTckCustomerArray", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int addTckCustomerArray(TCK_Ticket_WS TckPost, string SessionID) {
            object[] results = this.Invoke("addTckCustomerArray", new object[] {
                        TckPost,
                        SessionID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void addTckCustomerArrayAsync(TCK_Ticket_WS TckPost, string SessionID) {
            this.addTckCustomerArrayAsync(TckPost, SessionID, null);
        }
        
        /// <remarks/>
        public void addTckCustomerArrayAsync(TCK_Ticket_WS TckPost, string SessionID, object userState) {
            if ((this.addTckCustomerArrayOperationCompleted == null)) {
                this.addTckCustomerArrayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddTckCustomerArrayOperationCompleted);
            }
            this.InvokeAsync("addTckCustomerArray", new object[] {
                        TckPost,
                        SessionID}, this.addTckCustomerArrayOperationCompleted, userState);
        }
        
        private void OnaddTckCustomerArrayOperationCompleted(object arg) {
            if ((this.addTckCustomerArrayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addTckCustomerArrayCompleted(this, new addTckCustomerArrayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMailAimXtype", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendMailAimXtype(string from, string to, int CodRapportino, int TicketStatus_Template, string UserCrudTemplate, string MailTecnicoTemplate, string NomeTecnicoTemplate, int Attachments) {
            this.Invoke("SendMailAimXtype", new object[] {
                        from,
                        to,
                        CodRapportino,
                        TicketStatus_Template,
                        UserCrudTemplate,
                        MailTecnicoTemplate,
                        NomeTecnicoTemplate,
                        Attachments});
        }
        
        /// <remarks/>
        public void SendMailAimXtypeAsync(string from, string to, int CodRapportino, int TicketStatus_Template, string UserCrudTemplate, string MailTecnicoTemplate, string NomeTecnicoTemplate, int Attachments) {
            this.SendMailAimXtypeAsync(from, to, CodRapportino, TicketStatus_Template, UserCrudTemplate, MailTecnicoTemplate, NomeTecnicoTemplate, Attachments, null);
        }
        
        /// <remarks/>
        public void SendMailAimXtypeAsync(string from, string to, int CodRapportino, int TicketStatus_Template, string UserCrudTemplate, string MailTecnicoTemplate, string NomeTecnicoTemplate, int Attachments, object userState) {
            if ((this.SendMailAimXtypeOperationCompleted == null)) {
                this.SendMailAimXtypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMailAimXtypeOperationCompleted);
            }
            this.InvokeAsync("SendMailAimXtype", new object[] {
                        from,
                        to,
                        CodRapportino,
                        TicketStatus_Template,
                        UserCrudTemplate,
                        MailTecnicoTemplate,
                        NomeTecnicoTemplate,
                        Attachments}, this.SendMailAimXtypeOperationCompleted, userState);
        }
        
        private void OnSendMailAimXtypeOperationCompleted(object arg) {
            if ((this.SendMailAimXtypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMailAimXtypeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMailDBTemplate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendMailDBTemplate(JsonEmail _jsonMail, string[] _ArrayParamList) {
            this.Invoke("SendMailDBTemplate", new object[] {
                        _jsonMail,
                        _ArrayParamList});
        }
        
        /// <remarks/>
        public void SendMailDBTemplateAsync(JsonEmail _jsonMail, string[] _ArrayParamList) {
            this.SendMailDBTemplateAsync(_jsonMail, _ArrayParamList, null);
        }
        
        /// <remarks/>
        public void SendMailDBTemplateAsync(JsonEmail _jsonMail, string[] _ArrayParamList, object userState) {
            if ((this.SendMailDBTemplateOperationCompleted == null)) {
                this.SendMailDBTemplateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMailDBTemplateOperationCompleted);
            }
            this.InvokeAsync("SendMailDBTemplate", new object[] {
                        _jsonMail,
                        _ArrayParamList}, this.SendMailDBTemplateOperationCompleted, userState);
        }
        
        private void OnSendMailDBTemplateOperationCompleted(object arg) {
            if ((this.SendMailDBTemplateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMailDBTemplateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendTicketMailAim", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendTicketMailAim(JsonEmail _jsonMail) {
            this.Invoke("SendTicketMailAim", new object[] {
                        _jsonMail});
        }
        
        /// <remarks/>
        public void SendTicketMailAimAsync(JsonEmail _jsonMail) {
            this.SendTicketMailAimAsync(_jsonMail, null);
        }
        
        /// <remarks/>
        public void SendTicketMailAimAsync(JsonEmail _jsonMail, object userState) {
            if ((this.SendTicketMailAimOperationCompleted == null)) {
                this.SendTicketMailAimOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendTicketMailAimOperationCompleted);
            }
            this.InvokeAsync("SendTicketMailAim", new object[] {
                        _jsonMail}, this.SendTicketMailAimOperationCompleted, userState);
        }
        
        private void OnSendTicketMailAimOperationCompleted(object arg) {
            if ((this.SendTicketMailAimCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendTicketMailAimCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendTicketMailAim1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendTicketMailAim1(int TicketId, int TicketStatus, string UserCrud, TCK_Ticket_WS rapportini, string MailTecnico, string NomeTecnico, bool Responsabili, string TipoAllegato, string IdAllegato) {
            this.Invoke("SendTicketMailAim1", new object[] {
                        TicketId,
                        TicketStatus,
                        UserCrud,
                        rapportini,
                        MailTecnico,
                        NomeTecnico,
                        Responsabili,
                        TipoAllegato,
                        IdAllegato});
        }
        
        /// <remarks/>
        public void SendTicketMailAim1Async(int TicketId, int TicketStatus, string UserCrud, TCK_Ticket_WS rapportini, string MailTecnico, string NomeTecnico, bool Responsabili, string TipoAllegato, string IdAllegato) {
            this.SendTicketMailAim1Async(TicketId, TicketStatus, UserCrud, rapportini, MailTecnico, NomeTecnico, Responsabili, TipoAllegato, IdAllegato, null);
        }
        
        /// <remarks/>
        public void SendTicketMailAim1Async(int TicketId, int TicketStatus, string UserCrud, TCK_Ticket_WS rapportini, string MailTecnico, string NomeTecnico, bool Responsabili, string TipoAllegato, string IdAllegato, object userState) {
            if ((this.SendTicketMailAim1OperationCompleted == null)) {
                this.SendTicketMailAim1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendTicketMailAim1OperationCompleted);
            }
            this.InvokeAsync("SendTicketMailAim1", new object[] {
                        TicketId,
                        TicketStatus,
                        UserCrud,
                        rapportini,
                        MailTecnico,
                        NomeTecnico,
                        Responsabili,
                        TipoAllegato,
                        IdAllegato}, this.SendTicketMailAim1OperationCompleted, userState);
        }
        
        private void OnSendTicketMailAim1OperationCompleted(object arg) {
            if ((this.SendTicketMailAim1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendTicketMailAim1Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TCK_Ticket_WS {
        
        private int codRapportinoField;
        
        private string codClienteField;
        
        private string societàField;
        
        private string pIvaField;
        
        private string indirizzoField;
        
        private string capField;
        
        private string localitàField;
        
        private string provinciaField;
        
        private string telefonoField;
        
        private string faxField;
        
        private string emailField;
        
        private string matricolaField;
        
        private string scalaField;
        
        private int tipoImpiantoField;
        
        private string personaDaContattareField;
        
        private int tipoChiamataField;
        
        private int areaAssField;
        
        private string motivoChiamataField;
        
        private string noteField;
        
        private string guastoRilevatoField;
        
        private string lavoroEseguitoField;
        
        private bool interventoChiusoField;
        
        private string osservazioniField;
        
        private string dataInterventoField;
        
        private string dataInsField;
        
        private string editUserField;
        
        private string createdOnField;
        
        private string updatedOnField;
        
        private string userField;
        
        private string oreField;
        
        private int statusRptField;
        
        private int idField;
        
        private string incaricatoCliField;
        
        private string immagineTxtField;
        
        private string percorsoImmagineField;
        
        private int tCK_TipoRichiestaField;
        
        private int tCK_AreaCompetenzaField;
        
        private int tCK_TipoEsecuzionePresuntaField;
        
        private int tCK_TipoEsecuzioneField;
        
        private int tCK_StatusChiamataField;
        
        private int tCK_StatusChiamataChiusuraField;
        
        private int tCK_PrioritaRichiestaField;
        
        private int tCK_TipoChiusuraChiamataFatturaField;
        
        private string oraInzioInterventoField;
        
        private string oraFineInterventoField;
        
        private string nomePersonaRiferimentoField;
        
        private string telPersonaRiferimentoField;
        
        private string mailPersonaRiferimentoField;
        
        private float dirittoFissoField;
        
        private float tariffaOrariaField;
        
        private int speseViaggioKmField;
        
        private float speseViaggioEuroField;
        
        private float totaleEuroForfaitField;
        
        private string tCK_StatusChiamata_etichettaField;
        
        private string tCK_TipoRichiesta_etichettaField;
        
        private string tCK_AreaCompetenza_etichettaField;
        
        private string tCK_TipoEsecuzionePresunta_etichettaField;
        
        private string tCK_TipoEsecuzione_etichettaField;
        
        private string tCK_PrioritaRichiesta_etichettaField;
        
        private string imgFirmaClienteField;
        
        private string imgFirmaTecnicoField;
        
        private string firmaClienteField;
        
        private bool ticketFirmatoField;
        
        private string interventoPressoField;
        
        private string firmaTecnicoField;
        
        private string noteAnnullamentoTckField;
        
        private string noteTecnicoField;
        
        private string linkTckPdfField;
        
        private string tckInviatoAField;
        
        private string tCK_StatusChiamataChiusura_EtichettaField;
        
        private int totTecnici_TCKField;
        
        private float tempoInterventoTotaleField;
        
        private string uM_TempoField;
        
        private int statusControlloFattField;
        
        private string approvatoDaField;
        
        private int statusControlloRegistrazioneField;
        
        private int numeroRegistrazioneField;
        
        private string noteFatturazioneFinaleField;
        
        private int statusControlloFatturazioneFinaleField;
        
        private string societaField;
        
        private string denomField;
        
        private string indField;
        
        private string provField;
        
        private string locField;
        
        private string telField;
        
        private string riferimField;
        
        private string eMailField;
        
        private string codCliField;
        
        private string codArt_KingField;
        
        private int idIntervento_KingField;
        
        private string oggettoTCKField;
        
        private string tecniciField;
        
        private bool assegnatoCalendTecnicoField;
        
        private string inizioInterventoField;
        
        private string fineInterventoField;
        
        private string recurrenceInfoField;
        
        private string resourceIdField;
        
        private string iDExchangeField;
        
        private string tecnicoField;
        
        private int recurrenceEventField;
        
        private bool ticketPadreField;
        
        private string iDRecurrenceField;
        
        private string impiantoField;
        
        private string codiceImpiantoField;
        
        private string dataFineInterventoField;
        
        private bool prioritaCalendarioField;
        
        private string valoreColonnaField;
        
        private bool customerField;
        
        private string allegatiField;
        
        /// <remarks/>
        public int CodRapportino {
            get {
                return this.codRapportinoField;
            }
            set {
                this.codRapportinoField = value;
            }
        }
        
        /// <remarks/>
        public string CodCliente {
            get {
                return this.codClienteField;
            }
            set {
                this.codClienteField = value;
            }
        }
        
        /// <remarks/>
        public string Società {
            get {
                return this.societàField;
            }
            set {
                this.societàField = value;
            }
        }
        
        /// <remarks/>
        public string PIva {
            get {
                return this.pIvaField;
            }
            set {
                this.pIvaField = value;
            }
        }
        
        /// <remarks/>
        public string Indirizzo {
            get {
                return this.indirizzoField;
            }
            set {
                this.indirizzoField = value;
            }
        }
        
        /// <remarks/>
        public string Cap {
            get {
                return this.capField;
            }
            set {
                this.capField = value;
            }
        }
        
        /// <remarks/>
        public string Località {
            get {
                return this.localitàField;
            }
            set {
                this.localitàField = value;
            }
        }
        
        /// <remarks/>
        public string Provincia {
            get {
                return this.provinciaField;
            }
            set {
                this.provinciaField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Matricola {
            get {
                return this.matricolaField;
            }
            set {
                this.matricolaField = value;
            }
        }
        
        /// <remarks/>
        public string Scala {
            get {
                return this.scalaField;
            }
            set {
                this.scalaField = value;
            }
        }
        
        /// <remarks/>
        public int TipoImpianto {
            get {
                return this.tipoImpiantoField;
            }
            set {
                this.tipoImpiantoField = value;
            }
        }
        
        /// <remarks/>
        public string PersonaDaContattare {
            get {
                return this.personaDaContattareField;
            }
            set {
                this.personaDaContattareField = value;
            }
        }
        
        /// <remarks/>
        public int TipoChiamata {
            get {
                return this.tipoChiamataField;
            }
            set {
                this.tipoChiamataField = value;
            }
        }
        
        /// <remarks/>
        public int AreaAss {
            get {
                return this.areaAssField;
            }
            set {
                this.areaAssField = value;
            }
        }
        
        /// <remarks/>
        public string MotivoChiamata {
            get {
                return this.motivoChiamataField;
            }
            set {
                this.motivoChiamataField = value;
            }
        }
        
        /// <remarks/>
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        public string GuastoRilevato {
            get {
                return this.guastoRilevatoField;
            }
            set {
                this.guastoRilevatoField = value;
            }
        }
        
        /// <remarks/>
        public string LavoroEseguito {
            get {
                return this.lavoroEseguitoField;
            }
            set {
                this.lavoroEseguitoField = value;
            }
        }
        
        /// <remarks/>
        public bool InterventoChiuso {
            get {
                return this.interventoChiusoField;
            }
            set {
                this.interventoChiusoField = value;
            }
        }
        
        /// <remarks/>
        public string Osservazioni {
            get {
                return this.osservazioniField;
            }
            set {
                this.osservazioniField = value;
            }
        }
        
        /// <remarks/>
        public string DataIntervento {
            get {
                return this.dataInterventoField;
            }
            set {
                this.dataInterventoField = value;
            }
        }
        
        /// <remarks/>
        public string DataIns {
            get {
                return this.dataInsField;
            }
            set {
                this.dataInsField = value;
            }
        }
        
        /// <remarks/>
        public string EditUser {
            get {
                return this.editUserField;
            }
            set {
                this.editUserField = value;
            }
        }
        
        /// <remarks/>
        public string CreatedOn {
            get {
                return this.createdOnField;
            }
            set {
                this.createdOnField = value;
            }
        }
        
        /// <remarks/>
        public string UpdatedOn {
            get {
                return this.updatedOnField;
            }
            set {
                this.updatedOnField = value;
            }
        }
        
        /// <remarks/>
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public string Ore {
            get {
                return this.oreField;
            }
            set {
                this.oreField = value;
            }
        }
        
        /// <remarks/>
        public int StatusRpt {
            get {
                return this.statusRptField;
            }
            set {
                this.statusRptField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string IncaricatoCli {
            get {
                return this.incaricatoCliField;
            }
            set {
                this.incaricatoCliField = value;
            }
        }
        
        /// <remarks/>
        public string ImmagineTxt {
            get {
                return this.immagineTxtField;
            }
            set {
                this.immagineTxtField = value;
            }
        }
        
        /// <remarks/>
        public string PercorsoImmagine {
            get {
                return this.percorsoImmagineField;
            }
            set {
                this.percorsoImmagineField = value;
            }
        }
        
        /// <remarks/>
        public int TCK_TipoRichiesta {
            get {
                return this.tCK_TipoRichiestaField;
            }
            set {
                this.tCK_TipoRichiestaField = value;
            }
        }
        
        /// <remarks/>
        public int TCK_AreaCompetenza {
            get {
                return this.tCK_AreaCompetenzaField;
            }
            set {
                this.tCK_AreaCompetenzaField = value;
            }
        }
        
        /// <remarks/>
        public int TCK_TipoEsecuzionePresunta {
            get {
                return this.tCK_TipoEsecuzionePresuntaField;
            }
            set {
                this.tCK_TipoEsecuzionePresuntaField = value;
            }
        }
        
        /// <remarks/>
        public int TCK_TipoEsecuzione {
            get {
                return this.tCK_TipoEsecuzioneField;
            }
            set {
                this.tCK_TipoEsecuzioneField = value;
            }
        }
        
        /// <remarks/>
        public int TCK_StatusChiamata {
            get {
                return this.tCK_StatusChiamataField;
            }
            set {
                this.tCK_StatusChiamataField = value;
            }
        }
        
        /// <remarks/>
        public int TCK_StatusChiamataChiusura {
            get {
                return this.tCK_StatusChiamataChiusuraField;
            }
            set {
                this.tCK_StatusChiamataChiusuraField = value;
            }
        }
        
        /// <remarks/>
        public int TCK_PrioritaRichiesta {
            get {
                return this.tCK_PrioritaRichiestaField;
            }
            set {
                this.tCK_PrioritaRichiestaField = value;
            }
        }
        
        /// <remarks/>
        public int TCK_TipoChiusuraChiamataFattura {
            get {
                return this.tCK_TipoChiusuraChiamataFatturaField;
            }
            set {
                this.tCK_TipoChiusuraChiamataFatturaField = value;
            }
        }
        
        /// <remarks/>
        public string OraInzioIntervento {
            get {
                return this.oraInzioInterventoField;
            }
            set {
                this.oraInzioInterventoField = value;
            }
        }
        
        /// <remarks/>
        public string OraFineIntervento {
            get {
                return this.oraFineInterventoField;
            }
            set {
                this.oraFineInterventoField = value;
            }
        }
        
        /// <remarks/>
        public string NomePersonaRiferimento {
            get {
                return this.nomePersonaRiferimentoField;
            }
            set {
                this.nomePersonaRiferimentoField = value;
            }
        }
        
        /// <remarks/>
        public string TelPersonaRiferimento {
            get {
                return this.telPersonaRiferimentoField;
            }
            set {
                this.telPersonaRiferimentoField = value;
            }
        }
        
        /// <remarks/>
        public string MailPersonaRiferimento {
            get {
                return this.mailPersonaRiferimentoField;
            }
            set {
                this.mailPersonaRiferimentoField = value;
            }
        }
        
        /// <remarks/>
        public float DirittoFisso {
            get {
                return this.dirittoFissoField;
            }
            set {
                this.dirittoFissoField = value;
            }
        }
        
        /// <remarks/>
        public float TariffaOraria {
            get {
                return this.tariffaOrariaField;
            }
            set {
                this.tariffaOrariaField = value;
            }
        }
        
        /// <remarks/>
        public int SpeseViaggioKm {
            get {
                return this.speseViaggioKmField;
            }
            set {
                this.speseViaggioKmField = value;
            }
        }
        
        /// <remarks/>
        public float SpeseViaggioEuro {
            get {
                return this.speseViaggioEuroField;
            }
            set {
                this.speseViaggioEuroField = value;
            }
        }
        
        /// <remarks/>
        public float TotaleEuroForfait {
            get {
                return this.totaleEuroForfaitField;
            }
            set {
                this.totaleEuroForfaitField = value;
            }
        }
        
        /// <remarks/>
        public string TCK_StatusChiamata_etichetta {
            get {
                return this.tCK_StatusChiamata_etichettaField;
            }
            set {
                this.tCK_StatusChiamata_etichettaField = value;
            }
        }
        
        /// <remarks/>
        public string TCK_TipoRichiesta_etichetta {
            get {
                return this.tCK_TipoRichiesta_etichettaField;
            }
            set {
                this.tCK_TipoRichiesta_etichettaField = value;
            }
        }
        
        /// <remarks/>
        public string TCK_AreaCompetenza_etichetta {
            get {
                return this.tCK_AreaCompetenza_etichettaField;
            }
            set {
                this.tCK_AreaCompetenza_etichettaField = value;
            }
        }
        
        /// <remarks/>
        public string TCK_TipoEsecuzionePresunta_etichetta {
            get {
                return this.tCK_TipoEsecuzionePresunta_etichettaField;
            }
            set {
                this.tCK_TipoEsecuzionePresunta_etichettaField = value;
            }
        }
        
        /// <remarks/>
        public string TCK_TipoEsecuzione_etichetta {
            get {
                return this.tCK_TipoEsecuzione_etichettaField;
            }
            set {
                this.tCK_TipoEsecuzione_etichettaField = value;
            }
        }
        
        /// <remarks/>
        public string TCK_PrioritaRichiesta_etichetta {
            get {
                return this.tCK_PrioritaRichiesta_etichettaField;
            }
            set {
                this.tCK_PrioritaRichiesta_etichettaField = value;
            }
        }
        
        /// <remarks/>
        public string ImgFirmaCliente {
            get {
                return this.imgFirmaClienteField;
            }
            set {
                this.imgFirmaClienteField = value;
            }
        }
        
        /// <remarks/>
        public string ImgFirmaTecnico {
            get {
                return this.imgFirmaTecnicoField;
            }
            set {
                this.imgFirmaTecnicoField = value;
            }
        }
        
        /// <remarks/>
        public string FirmaCliente {
            get {
                return this.firmaClienteField;
            }
            set {
                this.firmaClienteField = value;
            }
        }
        
        /// <remarks/>
        public bool TicketFirmato {
            get {
                return this.ticketFirmatoField;
            }
            set {
                this.ticketFirmatoField = value;
            }
        }
        
        /// <remarks/>
        public string InterventoPresso {
            get {
                return this.interventoPressoField;
            }
            set {
                this.interventoPressoField = value;
            }
        }
        
        /// <remarks/>
        public string FirmaTecnico {
            get {
                return this.firmaTecnicoField;
            }
            set {
                this.firmaTecnicoField = value;
            }
        }
        
        /// <remarks/>
        public string NoteAnnullamentoTck {
            get {
                return this.noteAnnullamentoTckField;
            }
            set {
                this.noteAnnullamentoTckField = value;
            }
        }
        
        /// <remarks/>
        public string NoteTecnico {
            get {
                return this.noteTecnicoField;
            }
            set {
                this.noteTecnicoField = value;
            }
        }
        
        /// <remarks/>
        public string LinkTckPdf {
            get {
                return this.linkTckPdfField;
            }
            set {
                this.linkTckPdfField = value;
            }
        }
        
        /// <remarks/>
        public string TckInviatoA {
            get {
                return this.tckInviatoAField;
            }
            set {
                this.tckInviatoAField = value;
            }
        }
        
        /// <remarks/>
        public string TCK_StatusChiamataChiusura_Etichetta {
            get {
                return this.tCK_StatusChiamataChiusura_EtichettaField;
            }
            set {
                this.tCK_StatusChiamataChiusura_EtichettaField = value;
            }
        }
        
        /// <remarks/>
        public int TotTecnici_TCK {
            get {
                return this.totTecnici_TCKField;
            }
            set {
                this.totTecnici_TCKField = value;
            }
        }
        
        /// <remarks/>
        public float TempoInterventoTotale {
            get {
                return this.tempoInterventoTotaleField;
            }
            set {
                this.tempoInterventoTotaleField = value;
            }
        }
        
        /// <remarks/>
        public string UM_Tempo {
            get {
                return this.uM_TempoField;
            }
            set {
                this.uM_TempoField = value;
            }
        }
        
        /// <remarks/>
        public int StatusControlloFatt {
            get {
                return this.statusControlloFattField;
            }
            set {
                this.statusControlloFattField = value;
            }
        }
        
        /// <remarks/>
        public string ApprovatoDa {
            get {
                return this.approvatoDaField;
            }
            set {
                this.approvatoDaField = value;
            }
        }
        
        /// <remarks/>
        public int StatusControlloRegistrazione {
            get {
                return this.statusControlloRegistrazioneField;
            }
            set {
                this.statusControlloRegistrazioneField = value;
            }
        }
        
        /// <remarks/>
        public int NumeroRegistrazione {
            get {
                return this.numeroRegistrazioneField;
            }
            set {
                this.numeroRegistrazioneField = value;
            }
        }
        
        /// <remarks/>
        public string NoteFatturazioneFinale {
            get {
                return this.noteFatturazioneFinaleField;
            }
            set {
                this.noteFatturazioneFinaleField = value;
            }
        }
        
        /// <remarks/>
        public int StatusControlloFatturazioneFinale {
            get {
                return this.statusControlloFatturazioneFinaleField;
            }
            set {
                this.statusControlloFatturazioneFinaleField = value;
            }
        }
        
        /// <remarks/>
        public string societa {
            get {
                return this.societaField;
            }
            set {
                this.societaField = value;
            }
        }
        
        /// <remarks/>
        public string Denom {
            get {
                return this.denomField;
            }
            set {
                this.denomField = value;
            }
        }
        
        /// <remarks/>
        public string Ind {
            get {
                return this.indField;
            }
            set {
                this.indField = value;
            }
        }
        
        /// <remarks/>
        public string Prov {
            get {
                return this.provField;
            }
            set {
                this.provField = value;
            }
        }
        
        /// <remarks/>
        public string Loc {
            get {
                return this.locField;
            }
            set {
                this.locField = value;
            }
        }
        
        /// <remarks/>
        public string Tel {
            get {
                return this.telField;
            }
            set {
                this.telField = value;
            }
        }
        
        /// <remarks/>
        public string Riferim {
            get {
                return this.riferimField;
            }
            set {
                this.riferimField = value;
            }
        }
        
        /// <remarks/>
        public string EMail {
            get {
                return this.eMailField;
            }
            set {
                this.eMailField = value;
            }
        }
        
        /// <remarks/>
        public string CodCli {
            get {
                return this.codCliField;
            }
            set {
                this.codCliField = value;
            }
        }
        
        /// <remarks/>
        public string CodArt_King {
            get {
                return this.codArt_KingField;
            }
            set {
                this.codArt_KingField = value;
            }
        }
        
        /// <remarks/>
        public int IdIntervento_King {
            get {
                return this.idIntervento_KingField;
            }
            set {
                this.idIntervento_KingField = value;
            }
        }
        
        /// <remarks/>
        public string OggettoTCK {
            get {
                return this.oggettoTCKField;
            }
            set {
                this.oggettoTCKField = value;
            }
        }
        
        /// <remarks/>
        public string Tecnici {
            get {
                return this.tecniciField;
            }
            set {
                this.tecniciField = value;
            }
        }
        
        /// <remarks/>
        public bool AssegnatoCalendTecnico {
            get {
                return this.assegnatoCalendTecnicoField;
            }
            set {
                this.assegnatoCalendTecnicoField = value;
            }
        }
        
        /// <remarks/>
        public string InizioIntervento {
            get {
                return this.inizioInterventoField;
            }
            set {
                this.inizioInterventoField = value;
            }
        }
        
        /// <remarks/>
        public string FineIntervento {
            get {
                return this.fineInterventoField;
            }
            set {
                this.fineInterventoField = value;
            }
        }
        
        /// <remarks/>
        public string RecurrenceInfo {
            get {
                return this.recurrenceInfoField;
            }
            set {
                this.recurrenceInfoField = value;
            }
        }
        
        /// <remarks/>
        public string ResourceId {
            get {
                return this.resourceIdField;
            }
            set {
                this.resourceIdField = value;
            }
        }
        
        /// <remarks/>
        public string IDExchange {
            get {
                return this.iDExchangeField;
            }
            set {
                this.iDExchangeField = value;
            }
        }
        
        /// <remarks/>
        public string Tecnico {
            get {
                return this.tecnicoField;
            }
            set {
                this.tecnicoField = value;
            }
        }
        
        /// <remarks/>
        public int RecurrenceEvent {
            get {
                return this.recurrenceEventField;
            }
            set {
                this.recurrenceEventField = value;
            }
        }
        
        /// <remarks/>
        public bool TicketPadre {
            get {
                return this.ticketPadreField;
            }
            set {
                this.ticketPadreField = value;
            }
        }
        
        /// <remarks/>
        public string IDRecurrence {
            get {
                return this.iDRecurrenceField;
            }
            set {
                this.iDRecurrenceField = value;
            }
        }
        
        /// <remarks/>
        public string Impianto {
            get {
                return this.impiantoField;
            }
            set {
                this.impiantoField = value;
            }
        }
        
        /// <remarks/>
        public string CodiceImpianto {
            get {
                return this.codiceImpiantoField;
            }
            set {
                this.codiceImpiantoField = value;
            }
        }
        
        /// <remarks/>
        public string DataFineIntervento {
            get {
                return this.dataFineInterventoField;
            }
            set {
                this.dataFineInterventoField = value;
            }
        }
        
        /// <remarks/>
        public bool PrioritaCalendario {
            get {
                return this.prioritaCalendarioField;
            }
            set {
                this.prioritaCalendarioField = value;
            }
        }
        
        /// <remarks/>
        public string ValoreColonna {
            get {
                return this.valoreColonnaField;
            }
            set {
                this.valoreColonnaField = value;
            }
        }
        
        /// <remarks/>
        public bool Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        public string Allegati {
            get {
                return this.allegatiField;
            }
            set {
                this.allegatiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class JsonEmail {
        
        private string fromField;
        
        private string toField;
        
        private string oggettoMailField;
        
        private string codParametroTemplateField;
        
        private object arrayParamField;
        
        /// <remarks/>
        public string from {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        public string to {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public string OggettoMail {
            get {
                return this.oggettoMailField;
            }
            set {
                this.oggettoMailField = value;
            }
        }
        
        /// <remarks/>
        public string CodParametroTemplate {
            get {
                return this.codParametroTemplateField;
            }
            set {
                this.codParametroTemplateField = value;
            }
        }
        
        /// <remarks/>
        public object ArrayParam {
            get {
                return this.arrayParamField;
            }
            set {
                this.arrayParamField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void converttodayswebCompletedEventHandler(object sender, converttodayswebCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class converttodayswebCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal converttodayswebCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void MultiplicationCompletedEventHandler(object sender, MultiplicationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MultiplicationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MultiplicationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void addTckCustomerCompletedEventHandler(object sender, addTckCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addTckCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addTckCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void addTckCustomerArrayCompletedEventHandler(object sender, addTckCustomerArrayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addTckCustomerArrayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addTckCustomerArrayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SendMailAimXtypeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SendMailDBTemplateCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SendTicketMailAimCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SendTicketMailAim1CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591