//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da uno strumento.
//
//     Le modifiche a questo file possono causare un comportamento non corretto e verranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTRA
{


    public partial class Invio_Controllo_Fatturazione_Finale
    {
    }
}
